AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  EnvironmentType:
    Description: The environment type (prod or dev)
    Type: String
    Default: dev
    AllowedValues:
      - prod
      - dev
    ConstraintDescription: must be a prod or dev

Resources:
  SpiderQueue:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: 1209600
      VisibilityTimeout: 300
      QueueName: !Sub caseharvester_spider_queue_${EnvironmentType}

Outputs:
  SpiderQueueName:
    Description: Spider queue name
    Value: !GetAtt SpiderQueue.QueueName
    Export:
      Name: !Sub ${AWS::StackName}-SpiderQueueName
