AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  DatabasePassword:
    Type: String
    NoEcho: True
  DatabaseUsername:
    Type: String
    NoEcho: True
  DatabaseName:
    Type: String
    Default: mjcs
  StaticStackName:
    Description: Name of the static stack, for getting database and S3 bucket details
    Type: String
  ScraperStackName:
    Description: Name of the scraper stack, for getting scraper queue name
    Type: String
  DockerRepoStackName:
    Description: Name of the docker repo stack, for getting repository name
    Type: String
  EnvironmentType:
    Description: The environment type (prod or dev)
    Type: String
    Default: dev
    AllowedValues:
      - prod
      - dev
    ConstraintDescription: must be a prod or dev
  AWSRegion:
    Description: AWS Region
    Type: String
    Default: us-east-1

Resources:
  SpiderTaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub mjcs_ecs_spider_task_role_${EnvironmentType}
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSQSFullAccess

  ScheduledSpiderTask:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - Name: !Sub mjcs_spider_container_${EnvironmentType}
          Command: [ "python", "-u", "scheduled_spider.py" ]
          Environment:
            - Name: DOCKER_TASK
              Value: true
            - Name: MJCS_DATABASE_URL
              Value: !Sub
                - postgresql://${db_user}:${db_pw}@${db_addr}/${db_name}
                - db_user: !Ref DatabaseUsername
                  db_pw: !Ref DatabasePassword
                  db_addr:
                    Fn::ImportValue: !Sub ${StaticStackName}-DatabaseHostname
                  db_name: !Ref DatabaseName
            - Name: SPIDER_QUEUE_NAME
              Value: !GetAtt SpiderQueue.QueueName
            - Name: SCRAPER_QUEUE_NAME
              Value:
                Fn::ImportValue: !Sub ${ScraperStackName}-ScraperQueueName
          Image: !Sub
            - ${AWS::AccountId}.dkr.ecr.${AWSRegion}.amazonaws.com/${repo_name}
            - repo_name:
                Fn::ImportValue: !Sub ${DockerRepoStackName}-DockerRepoName
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-create-group: true
              awslogs-region: !Ref AWSRegion
              awslogs-group: !Sub caseharvester-spider-${EnvironmentType}
              awslogs-stream-prefix: caseharvester-spider-logs
      RequiresCompatibilities:
        - FARGATE
      Cpu: 1024
      Memory: 2048
      ExecutionRoleArn:
        Fn::ImportValue: !Sub ${StaticStackName}-ExecutionRoleArn
      NetworkMode: awsvpc
      TaskRoleArn: !GetAtt SpiderTaskRole.Arn

  SpiderQueue:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: 1209600
      VisibilityTimeout: 300
      QueueName: !Sub mjcs_spider_queue_${EnvironmentType}

  DailySpiderTrigger:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub daily_spider_trigger_${EnvironmentType}
      Description: Spider for cases filed in the last month (trigger)
      ScheduleExpression: cron(0 4 * * ? *)  # midnight ET
      Targets:
        - Id: spider_queue_target
          Arn: !GetAtt SpiderQueue.Arn
          Input: '{ "days_ago_start": 0, "days_ago_end": 30 }'
  
  DailySpiderRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub daily_spider_${EnvironmentType}
      Description: Spider for cases filed in the last month
      ScheduleExpression: cron(5 4 * * ? *)  # 5 past midnight ET
      Targets:
        - Id: spider_ecs_task_target
          Arn:
            Fn::ImportValue: !Sub ${StaticStackName}-ECSClusterArn
          RoleArn:
            Fn::ImportValue: !Sub ${StaticStackName}-ExecutionRoleArn
          EcsParameters:
            LaunchType: FARGATE
            TaskDefinitionArn: !Ref ScheduledSpiderTask
            TaskCount: 1
            NetworkConfiguration:
              AwsVpcConfiguration:
                AssignPublicIp: DISABLED
                SecurityGroups:
                  - Fn::ImportValue: !Sub ${StaticStackName}-VPCDefaultSecurityGroupId
                Subnets:
                  - Fn::ImportValue: !Sub ${StaticStackName}-VPCPrivateSubnet1Id
                  - Fn::ImportValue: !Sub ${StaticStackName}-VPCPrivateSubnet2Id
  
  WeeklySpiderTrigger:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub weekly_spider_trigger_${EnvironmentType}
      Description: Every week, spider for cases filed in the last 6 months (trigger)
      ScheduleExpression: cron(0 4 ? * SUN *)  # Sunday 00:00 ET
      Targets:
        - Id: spider_queue_target
          Arn: !GetAtt SpiderQueue.Arn
          Input: '{ "days_ago_start": 31, "days_ago_end": 182 }'
  
  WeeklySpiderRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub weekly_spider_${EnvironmentType}
      Description: Every week, spider for cases filed in the last 6 months
      ScheduleExpression: cron(5 4 ? * SUN *)  # Sunday 00:00 ET
      Targets:
        - Id: spider_ecs_task_target
          Arn:
            Fn::ImportValue: !Sub ${StaticStackName}-ECSClusterArn
          RoleArn:
            Fn::ImportValue: !Sub ${StaticStackName}-ExecutionRoleArn
          EcsParameters:
            LaunchType: FARGATE
            TaskDefinitionArn: !Ref ScheduledSpiderTask
            TaskCount: 1
            NetworkConfiguration:
              AwsVpcConfiguration:
                AssignPublicIp: DISABLED
                SecurityGroups:
                  - Fn::ImportValue: !Sub ${StaticStackName}-VPCDefaultSecurityGroupId
                Subnets:
                  - Fn::ImportValue: !Sub ${StaticStackName}-VPCPrivateSubnet1Id
                  - Fn::ImportValue: !Sub ${StaticStackName}-VPCPrivateSubnet2Id

  MonthlySpiderTrigger:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub monthly_spider_trigger_${EnvironmentType}
      Description: Every month, spider for cases filed in the last year (trigger)
      ScheduleExpression: cron(0 4 1 * ? *)  # 1st of month 00:00 ET
      Targets:
        - Id: spider_queue_target
          Arn: !GetAtt SpiderQueue.Arn
          Input: '{ "days_ago_start": 183, "days_ago_end": 365 }'

  MonthlySpiderRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub monthly_spider_${EnvironmentType}
      Description: Every month, spider for cases filed in the last year
      ScheduleExpression: cron(5 4 1 * ? *)  # 1st of month 00:00 ET
      Targets:
        - Id: spider_ecs_task_target
          Arn:
            Fn::ImportValue: !Sub ${StaticStackName}-ECSClusterArn
          RoleArn:
            Fn::ImportValue: !Sub ${StaticStackName}-ExecutionRoleArn
          EcsParameters:
            LaunchType: FARGATE
            TaskDefinitionArn: !Ref ScheduledSpiderTask
            TaskCount: 1
            NetworkConfiguration:
              AwsVpcConfiguration:
                AssignPublicIp: DISABLED
                SecurityGroups:
                  - Fn::ImportValue: !Sub ${StaticStackName}-VPCDefaultSecurityGroupId
                Subnets:
                  - Fn::ImportValue: !Sub ${StaticStackName}-VPCPrivateSubnet1Id
                  - Fn::ImportValue: !Sub ${StaticStackName}-VPCPrivateSubnet2Id