AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  DatabasePassword:
    Type: String
    NoEcho: True
  DatabaseUsername:
    Type: String
    NoEcho: True
  DatabaseName:
    Type: String
    Default: mjcs
  StaticStackName:
    Description: Name of the static stack, for getting database and S3 bucket details
    Type: String
  EnvironmentType:
    Description: The environment type (prod or dev)
    Type: String
    Default: dev
    AllowedValues:
      - prod
      - dev
    ConstraintDescription: must be a prod or dev
  DatabaseUrl:
    Description: The URL of the database
    Type: String

Conditions:
  CreateProdResources: !Equals [!Ref EnvironmentType, prod]
  EmptyDatabaseUrl: !Equals [!Ref DatabaseUrl, '']

Resources:
  Parser:
    Type: AWS::Serverless::Function
    Properties:
      Handler: parser_lambda.lambda_handler
      Runtime: python3.8
      FunctionName: !Sub caseharvester_parser_${EnvironmentType}
      Policies: # TODO slim this down
        - AWSLambda_FullAccess
        - S3ReadPolicy:
            BucketName:
              Fn::ImportValue: !Sub ${StaticStackName}-CaseDetailsBucketName
        - AmazonSQSFullAccess
        - VPCAccessPolicy: {}
      CodeUri: ../pkg/parser
      MemorySize: 300
      Timeout: 900
      ReservedConcurrentExecutions:
        !If [CreateProdResources, 250, !Ref 'AWS::NoValue']
      DeadLetterQueue:
        Type: SQS
        TargetArn: !GetAtt ParserFailedQueue.Arn
      Environment:
        Variables:
          MJCS_DATABASE_URL: !If
            - EmptyDatabaseUrl
            - !Sub
              - postgresql://${DatabaseUsername}:${DatabasePassword}@${db_addr}/${DatabaseName}
              - db_addr:
                  Fn::ImportValue: !Sub ${StaticStackName}-DatabaseHostname
            - !Ref DatabaseUrl
          CASE_DETAILS_BUCKET:
            Fn::ImportValue: !Sub ${StaticStackName}-CaseDetailsBucketName
          PARSER_FAILED_QUEUE_NAME: !GetAtt ParserFailedQueue.QueueName
          PARSER_TRIGGER_ARN: !Ref ParserTrigger
      Events:
        SNSTrigger:
          Type: SNS
          Properties:
            Topic: !Ref ParserTrigger
        SQSTrigger:
          Type: SQS
          Properties:
            BatchSize: 200
            MaximumBatchingWindowInSeconds: 300
            Queue: !GetAtt ParserQueue.Arn

  ParserTrigger:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub caseharvester_parser_trigger_${EnvironmentType}

  ParserS3Permission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:*
      FunctionName: !Ref Parser
      Principal: s3.amazonaws.com
      SourceArn:
        Fn::ImportValue: !Sub ${StaticStackName}-CaseDetailsBucketArn

  ParserFailedQueue:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: 1209600
      VisibilityTimeout: 30
      QueueName: !Sub caseharvester_parser_failed_queue_${EnvironmentType}

  ParserQueue:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: 1209600 # 14 days
      VisibilityTimeout: 5400 # 6x lambda timeout (1.5 hr)
      QueueName: !Sub caseharvester_parser_queue_${EnvironmentType}
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt ParserFailedQueue.Arn
        maxReceiveCount: 5

Outputs:
  ParserArn:
    Description: ARN of Parser lambda function
    Value: !GetAtt Parser.Arn
    Export:
      Name: !Sub ${AWS::StackName}-ParserArn
  ParserTriggerArn:
    Description: ARN of the SNS topic to trigger Parser lambda
    Value: !Ref ParserTrigger
    Export:
      Name: !Sub ${AWS::StackName}-ParserTriggerArn
  ParserFailedQueueName:
    Description: Name of the Parser lambda DLQ
    Value: !GetAtt ParserFailedQueue.QueueName
    Export:
      Name: !Sub ${AWS::StackName}-ParserFailedQueueName
  ParserQueueName:
    Description: General purpose queue for parsing programs
    Value: !GetAtt ParserQueue.QueueName
    Export:
      Name: !Sub ${AWS::StackName}-ParserQueueName
