AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  DatabasePassword:
    Type: String
    NoEcho: True
  DatabaseUsername:
    Type: String
    NoEcho: True
  DatabaseName:
    Type: String
    Default: mjcs
  StaticStackName:
    Description: Name of the static stack
    Type: String
  DockerRepoStackName:
    Description: Name of the docker repo stack
    Type: String
  EnvironmentType:
    Description: The environment type (prod or dev)
    Type: String
    Default: dev
    AllowedValues:
      - prod
      - dev
    ConstraintDescription: must be a prod or dev
  DatabaseUrl:
    Description: The URL of the database
    Type: String

Conditions:
  EmptyDatabaseUrl: !Equals [!Ref DatabaseUrl, '']

Resources:
  ScraperQueue:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: 1209600
      VisibilityTimeout: 300
      QueueName: !Sub caseharvester_scraper_queue_${EnvironmentType}

Outputs:
  ScraperQueueName:
    Description: Scraper queue name
    Value: !GetAtt ScraperQueue.QueueName
    Export:
      Name: !Sub ${AWS::StackName}-ScraperQueueName
  ScraperQueueArn:
    Description: Scraper queue ARN
    Value: !GetAtt ScraperQueue.Arn
    Export:
      Name: !Sub ${AWS::StackName}-ScraperQueueArn
