AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  DatabasePassword:
    Type: String
    NoEcho: True
  DatabaseUsername:
    Type: String
    NoEcho: True
  DatabaseName:
    Type: String
    Default: mjcs
  StaticStackName:
    Description: Name of the static stack, for getting database and S3 bucket details
    Type: String
  DockerRepoStackName:
    Description: Name of the docker repo stack, for getting repository name
    Type: String
  EnvironmentType:
    Description: The environment type (prod or dev)
    Type: String
    Default: dev
    AllowedValues:
      - prod
      - dev
    ConstraintDescription: must be a prod or dev
  AWSRegion:
    Description: AWS Region
    Type: String
    Default: us-east-1

Resources:
  ScraperQueue:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: 1209600
      VisibilityTimeout: 300
      QueueName: !Sub mjcs_scraper_queue_${EnvironmentType}

  ScraperTaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub mjcs_ecs_scraper_task_role_${EnvironmentType}
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSQSFullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess

  ScraperService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: !Sub mjcs_scraper_service_${EnvironmentType}
      Cluster:
        Fn::ImportValue: !Sub ${StaticStackName}-ECSClusterArn
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
            - Fn::ImportValue: !Sub ${StaticStackName}-VPCDefaultSecurityGroupId
          Subnets:
            - Fn::ImportValue: !Sub ${StaticStackName}-VPCPublicSubnet1Id
            - Fn::ImportValue: !Sub ${StaticStackName}-VPCPublicSubnet2Id
      TaskDefinition: !Ref ScraperServiceTask
  
  ScraperServiceTask:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - Name: !Sub mjcs_scraper_container_${EnvironmentType}
          Command:
            - python
            - -u
            - case_harvester.py
            - --environment
            - !Sub ${EnvironmentType}
            - scraper
            - --service
          Environment:
            - Name: MJCS_DATABASE_URL
              Value: !Sub
                - postgresql://${db_user}:${db_pw}@${db_addr}/${db_name}
                - db_user: !Ref DatabaseUsername
                  db_pw: !Ref DatabasePassword
                  db_addr:
                    Fn::ImportValue: !Sub ${StaticStackName}-DatabaseHostname
                  db_name: !Ref DatabaseName
            - Name: SCRAPER_QUEUE_NAME
              Value: !GetAtt ScraperQueue.QueueName
            - Name: CASE_DETAILS_BUCKET
              Value:
                Fn::ImportValue: !Sub ${StaticStackName}-CaseDetailsBucketName
          Image: !Sub
            - ${AWS::AccountId}.dkr.ecr.${AWSRegion}.amazonaws.com/${repo_name}
            - repo_name:
                Fn::ImportValue: !Sub ${DockerRepoStackName}-DockerRepoName
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-create-group: true
              awslogs-region: !Ref AWSRegion
              awslogs-group: !Sub caseharvester-scraper-service-${EnvironmentType}
              awslogs-stream-prefix: caseharvester-scraper-service-logs
      RequiresCompatibilities:
        - FARGATE
      Cpu: 1024
      Memory: 2048
      ExecutionRoleArn:
        Fn::ImportValue: !Sub ${StaticStackName}-ExecutionRoleArn
      NetworkMode: awsvpc
      TaskRoleArn: !GetAtt ScraperTaskRole.Arn

  DailyScraperTask:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - Name: !Sub mjcs_scraper_container_${EnvironmentType}
          Command:
            - python
            - -u
            - case_harvester.py
            - --environment
            - !Sub ${EnvironmentType}
            - scraper
            - --stale
          Environment:
            - Name: MJCS_DATABASE_URL
              Value: !Sub
                - postgresql://${db_user}:${db_pw}@${db_addr}/${db_name}
                - db_user: !Ref DatabaseUsername
                  db_pw: !Ref DatabasePassword
                  db_addr:
                    Fn::ImportValue: !Sub ${StaticStackName}-DatabaseHostname
                  db_name: !Ref DatabaseName
            - Name: SCRAPER_QUEUE_NAME
              Value: !GetAtt ScraperQueue.QueueName
            - Name: CASE_DETAILS_BUCKET
              Value:
                Fn::ImportValue: !Sub ${StaticStackName}-CaseDetailsBucketName
          Image: !Sub
            - ${AWS::AccountId}.dkr.ecr.${AWSRegion}.amazonaws.com/${repo_name}
            - repo_name:
                Fn::ImportValue: !Sub ${DockerRepoStackName}-DockerRepoName
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-create-group: true
              awslogs-region: !Ref AWSRegion
              awslogs-group: !Sub caseharvester-scraper-daily-${EnvironmentType}
              awslogs-stream-prefix: caseharvester-scraper-daily-logs
      RequiresCompatibilities:
        - FARGATE
      Cpu: 1024
      Memory: 2048
      ExecutionRoleArn:
        Fn::ImportValue: !Sub ${StaticStackName}-ExecutionRoleArn
      NetworkMode: awsvpc
      TaskRoleArn: !GetAtt ScraperTaskRole.Arn

  DailyScraperRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub daily_scraper_${EnvironmentType}
      Description: Daily rescrape cases based on case age
      ScheduleExpression: cron(0 22 * * ? *)  # 6pm ET
      Targets:
        - Id: scraper_ecs_task_target
          Arn:
            Fn::ImportValue: !Sub ${StaticStackName}-ECSClusterArn
          RoleArn:
            Fn::ImportValue: !Sub ${StaticStackName}-ExecutionRoleArn
          EcsParameters:
            LaunchType: FARGATE
            TaskDefinitionArn: !Ref DailyScraperTask
            TaskCount: 1
            NetworkConfiguration:
              AwsVpcConfiguration:
                AssignPublicIp: ENABLED
                SecurityGroups:
                  - Fn::ImportValue: !Sub ${StaticStackName}-VPCDefaultSecurityGroupId
                Subnets:
                  - Fn::ImportValue: !Sub ${StaticStackName}-VPCPublicSubnet1Id
                  - Fn::ImportValue: !Sub ${StaticStackName}-VPCPublicSubnet2Id

Outputs:
  ScraperQueueName:
    Description: Scraper queue name
    Value: !GetAtt ScraperQueue.QueueName
    Export:
      Name: !Sub ${AWS::StackName}-ScraperQueueName