AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  DatabasePassword:
    Type: String
    NoEcho: True
  DatabaseUsername:
    Type: String
    NoEcho: True
  DatabaseName:
    Type: String
    Default: mjcs
  StaticStackName:
    Description: Name of the static stack, for getting database and S3 bucket details
    Type: String
  EnvironmentType:
    Description: The environment type (prod or dev)
    Type: String
    Default: dev
    AllowedValues:
      - prod
      - dev
    ConstraintDescription: must be a prod or dev

Resources:
  Scraper:
    Type: AWS::Serverless::Function
    Properties:
      Handler: scraper_lambda.lambda_handler
      Runtime: python3.6
      Policies:
        - AWSLambdaFullAccess
        - S3CrudPolicy:
            BucketName:
              Fn::ImportValue: !Sub ${StaticStackName}-CaseDetailsBucketName
        - AmazonSQSFullAccess
        - VPCAccessPolicy: {}
      CodeUri: ../pkg/scraper
      MemorySize: 320
      Timeout: 900
      ReservedConcurrentExecutions: 10
      Environment:
        Variables:
          MJCS_DATABASE_URL: !Sub
            - postgresql://${db_user}:${db_pw}@${db_addr}/${db_name}
            - db_user: !Ref DatabaseUsername
              db_pw: !Ref DatabasePassword
              db_addr:
                Fn::ImportValue: !Sub ${StaticStackName}-DatabaseHostname
              db_name: !Ref DatabaseName
          CASE_DETAILS_BUCKET:
            Fn::ImportValue: !Sub ${StaticStackName}-CaseDetailsBucketName
          SCRAPER_DYNAMODB_TABLE_NAME: !Ref ScraperWorkerTable
          SCRAPER_QUEUE_ALARM_NAME: !Ref ScraperItemsAvailableAlarm
          SCRAPER_FAILED_QUEUE_NAME: !GetAtt ScraperFailedQueue.QueueName
          SCRAPER_QUEUE_NAME: !GetAtt ScraperQueue.QueueName
      VpcConfig:
        SecurityGroupIds:
          - Fn::ImportValue: !Sub ${StaticStackName}-VPCDefaultSecurityGroupId
        SubnetIds:
          - Fn::ImportValue: !Sub ${StaticStackName}-VPCPrivateSubnet1Id
          - Fn::ImportValue: !Sub ${StaticStackName}-VPCPrivateSubnet2Id
      Events:
        SNSTrigger:
          Type: SNS
          Properties:
            Topic: !Ref ScraperTrigger

  ScraperFailedQueue:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: 1209600
      VisibilityTimeout: 300
      QueueName: !Sub mjcs_scraper_failed_queue_${EnvironmentType}

  ScraperQueue:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: 1209600
      VisibilityTimeout: 300
      QueueName: !Sub mjcs_scraper_queue_${EnvironmentType}

  ScraperTrigger:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub mjcs_scraper_trigger_${EnvironmentType}

  ScraperItemsAvailableAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions:
        - !Ref ScraperTrigger
      AlarmDescription: Trigger MJCS scraper when items are available in queue
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: QueueName
          Value: !GetAtt ScraperQueue.QueueName
      EvaluationPeriods: '1'
      MetricName: ApproximateNumberOfMessagesVisible
      Namespace: AWS/SQS
      Period: '60' # seconds
      Statistic: Average
      Threshold: '0'

  ScraperWorkerTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  HourlyScraperRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub hourly_scraper_${EnvironmentType}
      Description: Trigger MJCS scraper once an hour
      ScheduleExpression: rate(1 hour)
      Targets:
        - Id: scraper_lambda_target
          Arn: !GetAtt Scraper.Arn
          Input: '{ "invocation": "scheduled" }'

  DailyScraperRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub daily_scraper_${EnvironmentType}
      Description: Trigger MJCS scraper once a day
      ScheduleExpression: cron(0 16 * * ? *)  # noon EST
      Targets:
        - Id: scraper_lambda_target
          Arn: !GetAtt Scraper.Arn
          Input: '{ "invocation": "scheduled", "rescrape": { "days_ago_start": 0, "days_ago_end": 30 } }'

  HourlyRulePermissions:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt Scraper.Arn
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt HourlyScraperRule.Arn

  DailyRulePermissions:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt Scraper.Arn
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt DailyScraperRule.Arn

Outputs:
  ScraperDynamoDBTableName:
    Description: Scraper DynamoDB Table name
    Value: !Ref ScraperWorkerTable
    Export:
      Name: !Sub ${AWS::StackName}-ScraperDynamoDBTableName
  ScraperQueueAlarmName:
    Description: Scraper queue alarm name
    Value: !Ref ScraperItemsAvailableAlarm
    Export:
      Name: !Sub ${AWS::StackName}-ScraperQueueAlarmName
  ScraperFailedQueueName:
    Description: Scraper failed queue name
    Value: !GetAtt ScraperFailedQueue.QueueName
    Export:
      Name: !Sub ${AWS::StackName}-ScraperFailedQueueName
  ScraperQueueName:
    Description: Scraper queue name
    Value: !GetAtt ScraperQueue.QueueName
    Export:
      Name: !Sub ${AWS::StackName}-ScraperQueueName
  ScraperArn:
    Description: ARN of Scraper lambda function
    Value: !GetAtt Scraper.Arn
    Export:
      Name: !Sub ${AWS::StackName}-ScraperArn
