"""Add redacted bool to column_metadata

Revision ID: 003e6ae1f9b5
Revises: 0baa1282aea4
Create Date: 2021-08-13 10:27:18.957414

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '003e6ae1f9b5'
down_revision = '0baa1282aea4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('column_metadata', sa.Column('redacted', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('column_metadata', 'redacted')
    # ### end Alembic commands ###
