"""Add possibly_expunged flag to ODYCRIM charges due to HB 1336

Revision ID: 015bf4aefeac
Revises: 3359002939a6
Create Date: 2021-04-29 17:40:18.045682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '015bf4aefeac'
down_revision = '3359002939a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('odycrim_charges', sa.Column('possibly_expunged', sa.Boolean(), server_default='false', nullable=False))
    op.drop_constraint('odycrim_charges_case_number_fkey', 'odycrim_charges')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('odycrim_charges_case_number_fkey', 'odycrim_charges', 'odycrim', ['case_number'], ['case_number'], ondelete='CASCADE')
    op.drop_column('odycrim_charges', 'possibly_expunged')
    # ### end Alembic commands ###
