"""Add user, usercdate fields to odycivil_judgment_comments

Revision ID: 025ecad5c330
Revises: da56ed9c2ee4
Create Date: 2021-03-02 16:39:58.072336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '025ecad5c330'
down_revision = 'da56ed9c2ee4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('odycivil_judgment_comments', sa.Column('user', sa.String(), nullable=True))
    op.add_column('odycivil_judgment_comments', sa.Column('usercdate', sa.Date(), nullable=True))
    op.add_column('odycivil_judgment_comments', sa.Column('usercdate_str', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('odycivil_judgment_comments', 'usercdate_str')
    op.drop_column('odycivil_judgment_comments', 'usercdate')
    op.drop_column('odycivil_judgment_comments', 'user')
    # ### end Alembic commands ###
