"""Added jail_cons_conc to odycrim_charges

Revision ID: 0327e0a1ca6a
Revises: d056a0d60a23
Create Date: 2021-07-02 14:48:26.795883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0327e0a1ca6a'
down_revision = 'bea2e05bd9fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('odycrim_charges', sa.Column('jail_cons_conc', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('odycrim_charges', 'jail_cons_conc')
    # ### end Alembic commands ###
