"""Add ODYCIVILDisposition

Revision ID: 03d0db20af8d
Revises: c53bda737bbe
Create Date: 2021-03-01 09:23:41.055781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03d0db20af8d'
down_revision = 'c53bda737bbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('odycivil_dispositions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disp_date', sa.Date(), nullable=True),
    sa.Column('disp_date_str', sa.String(), nullable=True),
    sa.Column('disp_code', sa.String(), nullable=True),
    sa.Column('disp_description', sa.String(), nullable=True),
    sa.Column('disp_stage', sa.String(), nullable=True),
    sa.Column('disp_stage_description', sa.String(), nullable=True),
    sa.Column('user', sa.String(), nullable=True),
    sa.Column('usercdate', sa.Date(), nullable=True),
    sa.Column('usercdate_str', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_number'], ['odycivil.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_odycivil_dispositions_case_number', 'odycivil_dispositions', ['case_number'], unique=False, postgresql_using='hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ixh_odycivil_dispositions_case_number', table_name='odycivil_dispositions')
    op.drop_table('odycivil_dispositions')
    # ### end Alembic commands ###
