"""Restore scrape_exempt

Revision ID: 04256934a246
Revises: d9fdeb7de827
Create Date: 2021-10-10 12:16:07.400019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04256934a246'
down_revision = 'd9fdeb7de827'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('scrape_exempt', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'scrape_exempt')
    # ### end Alembic commands ###
