"""Field updates for K

Revision ID: 0529952f8a2b
Revises: db345d84fc41
Create Date: 2021-10-12 08:35:18.813046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0529952f8a2b'
down_revision = 'db345d84fc41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('k_defendant_aliases')
    op.drop_index('ixh_k_plaintiffs_case_number', table_name='k_plaintiffs')
    op.drop_constraint('k_attorneys_plaintiff_id_fkey', 'k_attorneys', type_='foreignkey')
    op.drop_constraint('k_party_addresses_plaintiff_id_fkey', 'k_party_addresses', type_='foreignkey')
    op.drop_constraint('k_party_alias_plaintiff_id_fkey', 'k_party_alias', type_='foreignkey')
    op.drop_table('k_plaintiffs')
    op.drop_index('ixh_k_district_case_numbers_case_number', table_name='k_district_case_numbers')
    op.drop_table('k_district_case_numbers')
    op.drop_column('k_attorneys', 'plaintiff_id')
    op.drop_column('k_charges', 'converted_disposition')
    op.drop_column('k_charges', 'jail_start_date_str')
    op.drop_column('k_charges', 'jail_death')
    op.drop_column('k_charges', 'probable_cause')
    op.drop_column('k_charges', 'jail_suspended_term')
    op.drop_column('k_charges', 'agency_name')
    op.drop_column('k_charges', 'jail_cons_conc')
    op.drop_column('k_charges', 'jail_start_date')
    op.drop_column('k_charges', 'officer_id')
    op.add_column('k_defendants', sa.Column('race', sa.String(), nullable=True))
    op.add_column('k_defendants', sa.Column('sex', sa.String(), nullable=True))
    op.add_column('k_defendants', sa.Column('height', sa.Integer(), nullable=True))
    op.add_column('k_defendants', sa.Column('weight', sa.Integer(), nullable=True))
    op.add_column('k_defendants', sa.Column('DOB', sa.Date(), nullable=True))
    op.add_column('k_defendants', sa.Column('DOB_str', sa.String(), nullable=True))
    op.drop_column('k_defendants', 'business_org_name')
    op.drop_column('k_defendants', 'party_number')
    op.drop_column('k_documents', 'sequence_number')
    op.drop_column('k_party_addresses', 'plaintiff_id')
    op.drop_column('k_party_alias', 'plaintiff_id')
    op.drop_column('k_related_persons', 'business_org_name')
    op.drop_column('k_related_persons', 'party_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('k_related_persons', sa.Column('party_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('k_related_persons', sa.Column('business_org_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('k_party_alias', sa.Column('plaintiff_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('k_party_alias_plaintiff_id_fkey', 'k_party_alias', 'k_plaintiffs', ['plaintiff_id'], ['id'])
    op.add_column('k_party_addresses', sa.Column('plaintiff_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('k_party_addresses_plaintiff_id_fkey', 'k_party_addresses', 'k_plaintiffs', ['plaintiff_id'], ['id'])
    op.add_column('k_documents', sa.Column('sequence_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('k_defendants', sa.Column('party_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('k_defendants', sa.Column('business_org_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('k_defendants', 'DOB_str')
    op.drop_column('k_defendants', 'DOB')
    op.drop_column('k_defendants', 'weight')
    op.drop_column('k_defendants', 'height')
    op.drop_column('k_defendants', 'sex')
    op.drop_column('k_defendants', 'race')
    op.add_column('k_charges', sa.Column('officer_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('k_charges', sa.Column('jail_start_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('k_charges', sa.Column('jail_cons_conc', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('k_charges', sa.Column('agency_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('k_charges', sa.Column('jail_suspended_term', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('k_charges', sa.Column('probable_cause', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('k_charges', sa.Column('jail_death', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('k_charges', sa.Column('jail_start_date_str', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('k_charges', sa.Column('converted_disposition', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('k_attorneys', sa.Column('plaintiff_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('k_attorneys_plaintiff_id_fkey', 'k_attorneys', 'k_plaintiffs', ['plaintiff_id'], ['id'])
    op.create_table('k_district_case_numbers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('district_case_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('case_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['case_number'], ['k.case_number'], name='k_district_case_numbers_case_number_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='k_district_case_numbers_pkey')
    )
    op.create_index('ixh_k_district_case_numbers_case_number', 'k_district_case_numbers', ['case_number'], unique=False)
    op.create_table('k_plaintiffs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('party_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('party_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('business_org_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('case_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['case_number'], ['k.case_number'], name='k_plaintiffs_case_number_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='k_plaintiffs_pkey')
    )
    op.create_index('ixh_k_plaintiffs_case_number', 'k_plaintiffs', ['case_number'], unique=False)
    op.create_table('k_defendant_aliases',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('alias_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address_1', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address_2', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('zip_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('case_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['case_number'], ['k.case_number'], name='k_defendant_aliases_case_number_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='k_defendant_aliases_pkey')
    )
    op.create_index('ixh_k_defendant_aliases_case_number', 'k_defendant_aliases', ['case_number'], unique=False)
    # ### end Alembic commands ###
