"""Field updates for DSCIVIL

Revision ID: 05688275b38c
Revises: e9d408e7b639
Create Date: 2021-10-11 16:10:20.604520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05688275b38c'
down_revision = 'e9d408e7b639'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dscivil_judgments', sa.Column('possession_awardee', sa.String(), nullable=True))
    op.add_column('dscivil_judgments', sa.Column('awardee', sa.String(), nullable=True))
    op.drop_column('dscivil_related_persons', 'officer_id')
    op.drop_column('dscivil_related_persons', 'agency_sub_code')
    op.drop_column('dscivil_related_persons', 'agency_code')
    op.add_column('dscivil_trials', sa.Column('duration', sa.String(), nullable=True))
    op.drop_column('dscivil_trials', 'reason')
    op.drop_column('dscivil_trials', 'trial_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dscivil_trials', sa.Column('trial_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('dscivil_trials', sa.Column('reason', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('dscivil_trials', 'duration')
    op.add_column('dscivil_related_persons', sa.Column('agency_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('dscivil_related_persons', sa.Column('agency_sub_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('dscivil_related_persons', sa.Column('officer_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('dscivil_judgments', 'awardee')
    op.drop_column('dscivil_judgments', 'possession_awardee')
    # ### end Alembic commands ###
