"""Add label to column_metadata, rename constraint

Revision ID: 0baa1282aea4
Revises: baa609bd1160
Create Date: 2021-08-12 08:37:55.336601

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0baa1282aea4'
down_revision = 'baa609bd1160'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('column_metadata', sa.Column('label', sa.String(), nullable=True))
    op.execute('ALTER TABLE column_metadata RENAME CONSTRAINT column_metadata_column_name_width_pixels_key TO column_metadata_table_column_name_key')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE column_metadata RENAME CONSTRAINT column_metadata_table_column_name_key TO column_metadata_column_name_width_pixels_key')
    op.drop_column('column_metadata', 'label')
    # ### end Alembic commands ###
