"""Added some missing columns related to ODYCIVIL

Revision ID: 0be25bbbbd8c
Revises: c2f35a46de03
Create Date: 2021-03-01 17:30:00.832647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0be25bbbbd8c'
down_revision = 'c2f35a46de03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('odycivil_involved_parties', sa.Column('appearance_date', sa.Date(), nullable=True))
    op.add_column('odycivil_involved_parties', sa.Column('appearance_date_str', sa.String(), nullable=True))
    op.add_column('odycivil_involved_parties', sa.Column('removal_date', sa.Date(), nullable=True))
    op.add_column('odycivil_involved_parties', sa.Column('removal_date_str', sa.String(), nullable=True))
    op.add_column('odycivil_judgment_comments', sa.Column('dis_with_prej', sa.String(), nullable=True))
    op.add_column('odycivil_judgment_comments', sa.Column('in_favor_of_def', sa.String(), nullable=True))
    op.add_column('odycivil_judgment_comments', sa.Column('j_and_s_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('odycivil_judgment_comments', 'j_and_s_code')
    op.drop_column('odycivil_judgment_comments', 'in_favor_of_def')
    op.drop_column('odycivil_judgment_comments', 'dis_with_prej')
    op.drop_column('odycivil_involved_parties', 'removal_date_str')
    op.drop_column('odycivil_involved_parties', 'removal_date')
    op.drop_column('odycivil_involved_parties', 'appearance_date_str')
    op.drop_column('odycivil_involved_parties', 'appearance_date')
    # ### end Alembic commands ###
