"""Added servicefee to odycivil_judgment_comments

Revision ID: 0d1827f56503
Revises: 20ee054f0e99
Create Date: 2021-07-23 15:52:58.507218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d1827f56503'
down_revision = '20ee054f0e99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('odycivil_judgment_comments', sa.Column('servicefee', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('odycivil_judgment_comments', 'servicefee')
    # ### end Alembic commands ###
