"""Add jail_suspended_term column to odycrim_charges

Revision ID: 0ecfd4d83f6c
Revises: 950f3ef6e583
Create Date: 2019-08-27 17:43:21.288099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ecfd4d83f6c'
down_revision = '950f3ef6e583'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('odycrim_charges', sa.Column('jail_suspended_term', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('odycrim_charges', 'jail_suspended_term')
    # ### end Alembic commands ###
