"""Add more fields to k_charges

Revision ID: 10a283d18aa0
Revises: 98327ab2ad75
Create Date: 2021-08-23 08:24:24.002425

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '10a283d18aa0'
down_revision = '98327ab2ad75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('k_charges', sa.Column('fine_amount', sa.Numeric(), nullable=True))
    op.add_column('k_charges', sa.Column('fine_suspended_amount', sa.Numeric(), nullable=True))
    op.add_column('k_charges', sa.Column('fine_due', sa.String(), nullable=True))
    op.add_column('k_charges', sa.Column('fine_first_payment_due', sa.String(), nullable=True))
    op.add_column('k_charges', sa.Column('community_work_service_hours', sa.Numeric(), nullable=True))
    op.add_column('k_charges', sa.Column('community_work_service_complete_by', sa.String(), nullable=True))
    op.add_column('k_charges', sa.Column('community_work_service_report_to', sa.String(), nullable=True))
    op.add_column('k_charges', sa.Column('community_work_service_report_date', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('k_charges', 'community_work_service_report_date')
    op.drop_column('k_charges', 'community_work_service_report_to')
    op.drop_column('k_charges', 'community_work_service_complete_by')
    op.drop_column('k_charges', 'community_work_service_hours')
    op.drop_column('k_charges', 'fine_first_payment_due')
    op.drop_column('k_charges', 'fine_due')
    op.drop_column('k_charges', 'fine_suspended_amount')
    op.drop_column('k_charges', 'fine_amount')
    # ### end Alembic commands ###
