"""Create index for cases.checked_expunged_charges

Revision ID: 1312fd27db62
Revises: f39753ce0f30
Create Date: 2021-07-27 10:33:19.319965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1312fd27db62'
down_revision = 'f39753ce0f30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ixh_cases_checked_expunged_charges', 'cases', ['checked_expunged_charges'], unique=False, postgresql_using='hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ixh_cases_checked_expunged_charges', table_name='cases', postgresql_using='hash')
    # ### end Alembic commands ###
