"""Add MCCR models

Revision ID: 15f8d4786231
Revises: 26cf16acf1c0
Create Date: 2021-09-10 16:48:24.622210

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '15f8d4786231'
down_revision = '26cf16acf1c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mccr',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('court_system', sa.String(), nullable=True),
    sa.Column('sub_type', sa.String(), nullable=True),
    sa.Column('tracking_number', sa.String(), nullable=True),
    sa.Column('district_court_number', sa.String(), nullable=True),
    sa.Column('filing_date', sa.Date(), nullable=True),
    sa.Column('filing_date_str', sa.String(), nullable=True),
    sa.Column('case_status', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_number'], ['cases.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_number')
    )
    op.create_index('ixh_mccr_case_number', 'mccr', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('mccr_attorneys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('appearance_date', sa.Date(), nullable=True),
    sa.Column('appearance_date_str', sa.String(), nullable=True),
    sa.Column('removal_date', sa.Date(), nullable=True),
    sa.Column('removal_date_str', sa.String(), nullable=True),
    sa.Column('address_1', sa.String(), nullable=True),
    sa.Column('address_2', sa.String(), nullable=True),
    sa.Column('address_3', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_number'], ['mccr.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_mccr_attorneys_case_number', 'mccr_attorneys', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('mccr_charges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('charge_number', sa.Integer(), nullable=True),
    sa.Column('expunged', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('article_section_subsection', sa.String(), nullable=True),
    sa.Column('charge_description', sa.String(), nullable=True),
    sa.Column('citation_number', sa.String(), nullable=True),
    sa.Column('plea', sa.String(), nullable=True),
    sa.Column('disposition_text', sa.String(), nullable=True),
    sa.Column('disposition_date', sa.Date(), nullable=True),
    sa.Column('disposition_date_str', sa.String(), nullable=True),
    sa.Column('judge', sa.String(), nullable=True),
    sa.Column('imposed_life_times', sa.String(), nullable=True),
    sa.Column('imposed_years', sa.Integer(), nullable=True),
    sa.Column('imposed_months', sa.Integer(), nullable=True),
    sa.Column('imposed_days', sa.Integer(), nullable=True),
    sa.Column('imposed_consecutive', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('time_served_years', sa.Integer(), nullable=True),
    sa.Column('time_served_months', sa.Integer(), nullable=True),
    sa.Column('time_served_days', sa.Integer(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_number'], ['mccr.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_mccr_charges_case_number', 'mccr_charges', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('mccr_court_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('event_date_str', sa.String(), nullable=True),
    sa.Column('event_time', sa.Time(), nullable=True),
    sa.Column('event_time_str', sa.String(), nullable=True),
    sa.Column('judge', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('courtroom', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_number'], ['mccr.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_mccr_court_schedule_case_number', 'mccr_court_schedule', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('mccr_defendants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('DOB', sa.Date(), nullable=True),
    sa.Column('DOB_str', sa.String(), nullable=True),
    sa.Column('address_1', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_number'], ['mccr.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_mccr_defendants_case_number', 'mccr_defendants', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('mccr_dockets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('docket_date', sa.Date(), nullable=True),
    sa.Column('docket_date_str', sa.String(), nullable=True),
    sa.Column('docket_number', sa.Integer(), nullable=True),
    sa.Column('docket_description', sa.String(), nullable=True),
    sa.Column('docket_type', sa.String(), nullable=True),
    sa.Column('filed_by', sa.String(), nullable=True),
    sa.Column('docket_text', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_number'], ['mccr.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_mccr_dockets_case_number', 'mccr_dockets', ['case_number'], unique=False, postgresql_using='hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ixh_mccr_dockets_case_number', table_name='mccr_dockets', postgresql_using='hash')
    op.drop_table('mccr_dockets')
    op.drop_index('ixh_mccr_defendants_case_number', table_name='mccr_defendants', postgresql_using='hash')
    op.drop_table('mccr_defendants')
    op.drop_index('ixh_mccr_court_schedule_case_number', table_name='mccr_court_schedule', postgresql_using='hash')
    op.drop_table('mccr_court_schedule')
    op.drop_index('ixh_mccr_charges_case_number', table_name='mccr_charges', postgresql_using='hash')
    op.drop_table('mccr_charges')
    op.drop_index('ixh_mccr_attorneys_case_number', table_name='mccr_attorneys', postgresql_using='hash')
    op.drop_table('mccr_attorneys')
    op.drop_index('ixh_mccr_case_number', table_name='mccr', postgresql_using='hash')
    op.drop_table('mccr')
    # ### end Alembic commands ###
