"""Add mccr_remitters model

Revision ID: 193c09af9eb1
Revises: 7ffd37d6c99d
Create Date: 2021-09-20 13:01:47.607560

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '193c09af9eb1'
down_revision = '7ffd37d6c99d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mccr_bond_remitters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('remitter', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_number'], ['mccr.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_mccr_bond_remitters_case_number', 'mccr_bond_remitters', ['case_number'], unique=False, postgresql_using='hash')
    op.drop_column('mccr_bail_bonds', 'remitter')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mccr_bail_bonds', sa.Column('remitter', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index('ixh_mccr_bond_remitters_case_number', table_name='mccr_bond_remitters', postgresql_using='hash')
    op.drop_table('mccr_bond_remitters')
    # ### end Alembic commands ###
