"""More indexes for case table

Revision ID: 1c01c67345db
Revises: 1312fd27db62
Create Date: 2021-07-28 02:50:42.727723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c01c67345db'
down_revision = '1312fd27db62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_cases_detail_loc'), 'cases', ['detail_loc'], unique=False)
    op.create_index(op.f('ix_cases_last_parse'), 'cases', ['last_parse'], unique=False)
    op.create_index(op.f('ix_cases_last_scrape'), 'cases', ['last_scrape'], unique=False)
    op.create_index('ixh_cases_detail_loc', 'cases', ['detail_loc'], unique=False, postgresql_using='hash')
    op.create_index('ixh_cases_parse_exempt', 'cases', ['parse_exempt'], unique=False, postgresql_using='hash')
    op.create_index('ixh_cases_scrape_exempt', 'cases', ['scrape_exempt'], unique=False, postgresql_using='hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ixh_cases_scrape_exempt', table_name='cases', postgresql_using='hash')
    op.drop_index('ixh_cases_parse_exempt', table_name='cases', postgresql_using='hash')
    op.drop_index('ixh_cases_detail_loc', table_name='cases', postgresql_using='hash')
    op.drop_index(op.f('ix_cases_last_scrape'), table_name='cases')
    op.drop_index(op.f('ix_cases_last_parse'), table_name='cases')
    op.drop_index(op.f('ix_cases_detail_loc'), table_name='cases')
    # ### end Alembic commands ###
