"""Remove unused URL field from cases table

Revision ID: 1d128fd0312c
Revises: 10a283d18aa0
Create Date: 2021-08-30 10:07:47.163043

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1d128fd0312c'
down_revision = 'b1570fa6c264'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
