"""add duration column to dscivil_trial

Revision ID: 1fc42302345c
Revises: 2d0b5c6986f1
Create Date: 2018-05-08 14:07:38.639083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fc42302345c'
down_revision = '2d0b5c6986f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dscivil_trial', sa.Column('duration', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dscivil_trial', 'duration')
    # ### end Alembic commands ###
