"""add removal_date to cc_attorneys

Revision ID: 233cfe62cd05
Revises: 443341b4957e
Create Date: 2018-05-20 22:05:56.886050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '233cfe62cd05'
down_revision = '443341b4957e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cc_attorneys', sa.Column('removal_date', sa.Date(), nullable=True))
    op.add_column('cc_attorneys', sa.Column('removal_date_str', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cc_attorneys', 'removal_date_str')
    op.drop_column('cc_attorneys', 'removal_date')
    # ### end Alembic commands ###
