"""Add renewed field to mcci_judgments

Revision ID: 23a7ddcfc553
Revises: 62f52367e30c
Create Date: 2021-09-14 10:18:02.302169

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '23a7ddcfc553'
down_revision = '62f52367e30c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mcci_judgments', sa.Column('renewed', sa.Date(), nullable=True))
    op.add_column('mcci_judgments', sa.Column('renewed_str', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mcci_judgments', 'renewed_str')
    op.drop_column('mcci_judgments', 'renewed')
    # ### end Alembic commands ###
