"""Add pg_plaintiffs

Revision ID: 26cf16acf1c0
Revises: f1d79c03a365
Create Date: 2021-09-02 02:33:42.222573

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '26cf16acf1c0'
down_revision = 'f1d79c03a365'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pg_plaintiffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('party_number', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address_1', sa.String(), nullable=True),
    sa.Column('address_2', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_number'], ['pg.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_pg_plaintiffs_case_number', 'pg_plaintiffs', ['case_number'], unique=False, postgresql_using='hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ixh_pg_plaintiffs_case_number', table_name='pg_plaintiffs', postgresql_using='hash')
    op.drop_table('pg_plaintiffs')
    # ### end Alembic commands ###
