"""add dscivil_trial table

Revision ID: 2d0b5c6986f1
Revises: 575e78461360
Create Date: 2018-05-08 14:02:43.459772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d0b5c6986f1'
down_revision = '575e78461360'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dscivil_trial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_number', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('date_str', sa.String(), nullable=True),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('time_str', sa.String(), nullable=True),
    sa.Column('room', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_number'], ['cases.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dscivil_trial')
    # ### end Alembic commands ###
