"""drop scrape_exempt, parse_exempt, allow_unparsed_data

Revision ID: 30ac70fd7fe7
Revises: 23a7ddcfc553
Create Date: 2021-09-16 14:21:27.301795

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '30ac70fd7fe7'
down_revision = '23a7ddcfc553'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'allow_unparsed_data')
    op.drop_column('cases', 'scrape_exempt')
    op.drop_column('cases', 'parse_exempt')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('parse_exempt', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('cases', sa.Column('scrape_exempt', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('cases', sa.Column('allow_unparsed_data', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
