"""Add PGV models

Revision ID: 37666ebe1907
Revises: 30ac70fd7fe7
Create Date: 2021-09-19 12:11:13.280787

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '37666ebe1907'
down_revision = '30ac70fd7fe7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pgv',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('court_system', sa.String(), nullable=True),
    sa.Column('case_description', sa.String(), nullable=True),
    sa.Column('case_type', sa.String(), nullable=True),
    sa.Column('filing_date', sa.Date(), nullable=True),
    sa.Column('filing_date_str', sa.String(), nullable=True),
    sa.Column('case_status', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_number'], ['cases.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_number')
    )
    op.create_index('ixh_pgv_case_number', 'pgv', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('pgv_court_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('event_date_str', sa.String(), nullable=True),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('time_str', sa.String(), nullable=True),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('result_date', sa.Date(), nullable=True),
    sa.Column('result_date_str', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_number'], ['pgv.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_pgv_court_schedule_case_number', 'pgv_court_schedule', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('pgv_defendant_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alias_name', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_number'], ['pgv.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_pgv_defendant_aliases_case_number', 'pgv_defendant_aliases', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('pgv_defendants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('party_number', sa.Integer(), nullable=True),
    sa.Column('party_type', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address_1', sa.String(), nullable=True),
    sa.Column('address_2', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_number'], ['pgv.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_pgv_defendants_case_number', 'pgv_defendants', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('pgv_dockets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('date_str', sa.String(), nullable=True),
    sa.Column('document_name', sa.String(), nullable=True),
    sa.Column('docket_text', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_number'], ['pgv.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_pgv_dockets_case_number', 'pgv_dockets', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('pgv_judgments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('judgment_date', sa.Date(), nullable=True),
    sa.Column('judgment_date_str', sa.String(), nullable=True),
    sa.Column('status_date', sa.Date(), nullable=True),
    sa.Column('status_date_str', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('amount', sa.Numeric(), nullable=True),
    sa.Column('against', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_number'], ['pgv.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_pgv_judgments_case_number', 'pgv_judgments', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('pgv_other_parties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('party_type', sa.String(), nullable=True),
    sa.Column('party_number', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_number'], ['pgv.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_pgv_other_parties_case_number', 'pgv_other_parties', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('pgv_plaintiffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('party_number', sa.Integer(), nullable=True),
    sa.Column('party_type', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address_1', sa.String(), nullable=True),
    sa.Column('address_2', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_number'], ['pgv.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_pgv_plaintiffs_case_number', 'pgv_plaintiffs', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('pgv_attorneys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('attorney_type', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('defendant_id', sa.Integer(), nullable=True),
    sa.Column('plaintiff_id', sa.Integer(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_number'], ['pgv.case_number'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['defendant_id'], ['pgv_defendants.id'], ),
    sa.ForeignKeyConstraint(['plaintiff_id'], ['pgv_plaintiffs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_pgv_attorneys_case_number', 'pgv_attorneys', ['case_number'], unique=False, postgresql_using='hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ixh_pgv_attorneys_case_number', table_name='pgv_attorneys', postgresql_using='hash')
    op.drop_table('pgv_attorneys')
    op.drop_index('ixh_pgv_plaintiffs_case_number', table_name='pgv_plaintiffs', postgresql_using='hash')
    op.drop_table('pgv_plaintiffs')
    op.drop_index('ixh_pgv_other_parties_case_number', table_name='pgv_other_parties', postgresql_using='hash')
    op.drop_table('pgv_other_parties')
    op.drop_index('ixh_pgv_judgments_case_number', table_name='pgv_judgments', postgresql_using='hash')
    op.drop_table('pgv_judgments')
    op.drop_index('ixh_pgv_dockets_case_number', table_name='pgv_dockets', postgresql_using='hash')
    op.drop_table('pgv_dockets')
    op.drop_index('ixh_pgv_defendants_case_number', table_name='pgv_defendants', postgresql_using='hash')
    op.drop_table('pgv_defendants')
    op.drop_index('ixh_pgv_defendant_aliases_case_number', table_name='pgv_defendant_aliases', postgresql_using='hash')
    op.drop_table('pgv_defendant_aliases')
    op.drop_index('ixh_pgv_court_schedule_case_number', table_name='pgv_court_schedule', postgresql_using='hash')
    op.drop_table('pgv_court_schedule')
    op.drop_index('ixh_pgv_case_number', table_name='pgv', postgresql_using='hash')
    op.drop_table('pgv')
    # ### end Alembic commands ###
