"""Add retry_failed column to runs table

Revision ID: 3df211a638f7
Revises: e86f479e25e4
Create Date: 2018-08-20 15:01:43.097066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3df211a638f7'
down_revision = 'e86f479e25e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runs', sa.Column('retry_failed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'retry_failed')
    # ### end Alembic commands ###
