"""Add possibly_expunged flag to odytraf_charges, dscr_charges, dsk8_charges

Revision ID: 4394875fda45
Revises: 0b545c28e0a3
Create Date: 2021-07-22 14:09:27.681870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4394875fda45'
down_revision = '0b545c28e0a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dscr_charges', sa.Column('possibly_expunged', sa.Boolean(), server_default='false', nullable=False))
    op.alter_column('dscr_charges', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('dscr_charges_case_number_fkey', 'dscr_charges', type_='foreignkey')
    op.add_column('dsk8_charges', sa.Column('possibly_expunged', sa.Boolean(), server_default='false', nullable=False))
    op.alter_column('dsk8_charges', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('dsk8_charges_case_number_fkey', 'dsk8_charges', type_='foreignkey')
    op.add_column('odytraf_charges', sa.Column('possibly_expunged', sa.Boolean(), server_default='false', nullable=False))
    op.alter_column('odytraf_charges', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('odytraf_charges_case_number_fkey', 'odytraf_charges', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('odytraf_charges_case_number_fkey', 'odytraf_charges', 'odytraf', ['case_number'], ['case_number'], ondelete='CASCADE')
    op.alter_column('odytraf_charges', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('odytraf_charges', 'possibly_expunged')
    op.create_foreign_key('dsk8_charges_case_number_fkey', 'dsk8_charges', 'dsk8', ['case_number'], ['case_number'], ondelete='CASCADE')
    op.alter_column('dsk8_charges', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('dsk8_charges', 'possibly_expunged')
    op.create_foreign_key('dscr_charges_case_number_fkey', 'dscr_charges', 'dscr', ['case_number'], ['case_number'], ondelete='CASCADE')
    op.alter_column('dscr_charges', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('dscr_charges', 'possibly_expunged')
    # ### end Alembic commands ###
