"""Add active boolean to case table

Revision ID: 4baf21cf0e43
Revises: d74fb94c58b2
Create Date: 2020-06-22 15:03:41.360516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4baf21cf0e43'
down_revision = 'd74fb94c58b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('active', sa.Boolean(), default=True, nullable=False))
    print('Updating CC cases')
    op.execute(sa.text("""
        UPDATE cases
        SET active = False
        FROM cc
        WHERE cases.case_number = cc.case_number
            AND cc.case_status = 'Closed/Inactive'
    """))
    print('Updating DSCIVIL cases')
    op.execute(sa.text("""
        UPDATE cases
        SET active = False
        FROM dscivil
        WHERE cases.case_number = dscivil.case_number
            AND dscivil.case_status = 'CLOSED'
    """))
    print('Updating DSCR cases')
    op.execute(sa.text("""
        UPDATE cases
        SET active = False
        FROM dscr
        WHERE cases.case_number = dscr.case_number
            AND dscr.case_status IN ('INACTIVE DUE TO INCOMPETENCY', 'CLOSED')
    """))
    print('Updating DSK8 cases')
    op.execute(sa.text("""
        UPDATE cases
        SET active = False
        FROM dsk8
        WHERE cases.case_number = dsk8.case_number
            AND dsk8.case_status IN ('INACTIVE', 'CLOSED')
    """))
    print('Updating ODYCRIM cases')
    op.execute(sa.text("""
        UPDATE cases
        SET active = False
        FROM odycrim
        WHERE cases.case_number = odycrim.case_number
            AND odycrim.case_status IN (
                'Citation Voided',
                'Inactive / Incompetency',
                'Closed / Inactive',
                'Closed',
                'Completed'
            )
    """))
    print('Updating ODYTRAF cases')
    op.execute(sa.text("""
        UPDATE cases
        SET active = False
        FROM odytraf
        WHERE cases.case_number = odytraf.case_number
            AND odytraf.case_status IN (
                'Citation Voided',
                'Inactive / Incompetency',
                'Closed / Inactive',
                'Closed',
                'Expunged',
                'Inactive'
            )
    """))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'active')
    # ### end Alembic commands ###
