"""Add MCCI models

Revision ID: 62f52367e30c
Revises: 67507d5db7c9
Create Date: 2021-09-14 01:46:21.854993

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '62f52367e30c'
down_revision = '67507d5db7c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mcci',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('court_system', sa.String(), nullable=True),
    sa.Column('sub_type', sa.String(), nullable=True),
    sa.Column('filing_date', sa.Date(), nullable=True),
    sa.Column('filing_date_str', sa.String(), nullable=True),
    sa.Column('case_status', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_number'], ['cases.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_number')
    )
    op.create_index('ixh_mcci_case_number', 'mcci', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('mcci_court_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('date_str', sa.String(), nullable=True),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('time_str', sa.String(), nullable=True),
    sa.Column('judge', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('courtroom', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_number'], ['mcci.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_mcci_court_schedule_case_number', 'mcci_court_schedule', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('mcci_defendants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_number'], ['mcci.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_mcci_defendants_case_number', 'mcci_defendants', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('mcci_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('party', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_number'], ['mcci.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_mcci_aliases_case_number', 'mcci_aliases', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('mcci_dockets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('date_str', sa.String(), nullable=True),
    sa.Column('docket_number', sa.Integer(), nullable=True),
    sa.Column('docket_description', sa.String(), nullable=True),
    sa.Column('docket_type', sa.String(), nullable=True),
    sa.Column('filed_by', sa.String(), nullable=True),
    sa.Column('docket_text', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('ruling_judge', sa.String(), nullable=True),
    sa.Column('reference_docket', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_number'], ['mcci.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_mcci_dockets_case_number', 'mcci_dockets', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('mcci_audio_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audio_media', sa.String(), nullable=True),
    sa.Column('audio_start', sa.String(), nullable=True),
    sa.Column('audio_stop', sa.String(), nullable=True),
    sa.Column('docket_id', sa.Integer(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_number'], ['mcci.case_number'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['docket_id'], ['mcci_dockets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_mcci_audio_media_case_number', 'mcci_audio_media', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('mcci_interested_parties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_number'], ['mcci.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_mcci_interested_parties_case_number', 'mcci_interested_parties', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('mcci_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_number'], ['mcci.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_mcci_issues_case_number', 'mcci_issues', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('mcci_judgments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('date_str', sa.String(), nullable=True),
    sa.Column('amount', sa.Numeric(), nullable=True),
    sa.Column('debtor', sa.String(), nullable=True),
    sa.Column('party_role', sa.String(), nullable=True),
    sa.Column('entered', sa.Date(), nullable=True),
    sa.Column('entered_str', sa.String(), nullable=True),
    sa.Column('satisfied', sa.Date(), nullable=True),
    sa.Column('satisfied_str', sa.String(), nullable=True),
    sa.Column('vacated', sa.Date(), nullable=True),
    sa.Column('vacated_str', sa.String(), nullable=True),
    sa.Column('amended', sa.Date(), nullable=True),
    sa.Column('amended_str', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_number'], ['mcci.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_mcci_judgment_case_number', 'mcci_judgments', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('mcci_plaintiffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_number'], ['mcci.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_mcci_plaintiffs_case_number', 'mcci_plaintiffs', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('mcci_wards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_number'], ['mcci.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_mcci_wards_case_number', 'mcci_wards', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('mcci_garnishees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_number'], ['mcci.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_mcci_garnishees_case_number', 'mcci_garnishees', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('mcci_attorneys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('appearance_date', sa.Date(), nullable=True),
    sa.Column('appearance_date_str', sa.String(), nullable=True),
    sa.Column('removal_date', sa.Date(), nullable=True),
    sa.Column('removal_date_str', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('defendant_id', sa.Integer(), nullable=True),
    sa.Column('plaintiff_id', sa.Integer(), nullable=True),
    sa.Column('ward_id', sa.Integer(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_number'], ['mcci.case_number'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['defendant_id'], ['mcci_defendants.id'], ),
    sa.ForeignKeyConstraint(['plaintiff_id'], ['mcci_plaintiffs.id'], ),
    sa.ForeignKeyConstraint(['ward_id'], ['mcci_wards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_mcci_attorneys_case_number', 'mcci_attorneys', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('mcci_resident_agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('plaintiff_id', sa.Integer(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_number'], ['mcci.case_number'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plaintiff_id'], ['mcci_plaintiffs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_mcci_resident_agents_case_number', 'mcci_resident_agents', ['case_number'], unique=False, postgresql_using='hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ixh_mcci_resident_agents_case_number', table_name='mcci_resident_agents', postgresql_using='hash')
    op.drop_table('mcci_resident_agents')
    op.drop_index('ixh_mcci_attorneys_case_number', table_name='mcci_attorneys', postgresql_using='hash')
    op.drop_table('mcci_attorneys')
    op.drop_index('ixh_mcci_garnishees_case_number', table_name='mcci_garnishees', postgresql_using='hash')
    op.drop_table('mcci_garnishees')
    op.drop_index('ixh_mcci_wards_case_number', table_name='mcci_wards', postgresql_using='hash')
    op.drop_table('mcci_wards')
    op.drop_index('ixh_mcci_plaintiffs_case_number', table_name='mcci_plaintiffs', postgresql_using='hash')
    op.drop_table('mcci_plaintiffs')
    op.drop_index('ixh_mcci_judgment_case_number', table_name='mcci_judgments', postgresql_using='hash')
    op.drop_table('mcci_judgments')
    op.drop_index('ixh_mcci_issues_case_number', table_name='mcci_issues', postgresql_using='hash')
    op.drop_table('mcci_issues')
    op.drop_index('ixh_mcci_interested_parties_case_number', table_name='mcci_interested_parties', postgresql_using='hash')
    op.drop_table('mcci_interested_parties')
    op.drop_index('ixh_mcci_audio_media_case_number', table_name='mcci_audio_media', postgresql_using='hash')
    op.drop_table('mcci_audio_media')
    op.drop_index('ixh_mcci_dockets_case_number', table_name='mcci_dockets', postgresql_using='hash')
    op.drop_table('mcci_dockets')
    op.drop_index('ixh_mcci_aliases_case_number', table_name='mcci_aliases', postgresql_using='hash')
    op.drop_table('mcci_aliases')
    op.drop_index('ixh_mcci_defendants_case_number', table_name='mcci_defendants', postgresql_using='hash')
    op.drop_table('mcci_defendants')
    op.drop_index('ixh_mcci_court_schedule_case_number', table_name='mcci_court_schedule', postgresql_using='hash')
    op.drop_table('mcci_court_schedule')
    op.drop_index('ixh_mcci_case_number', table_name='mcci', postgresql_using='hash')
    op.drop_table('mcci')
    # ### end Alembic commands ###
