"""Fix to DSCP and K models

Revision ID: 66e022919043
Revises: d5cb6fe00424
Create Date: 2021-08-23 05:21:15.530640

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '66e022919043'
down_revision = 'd5cb6fe00424'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('k_defendant_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alias_name', sa.String(), nullable=True),
    sa.Column('address_1', sa.String(), nullable=True),
    sa.Column('address_2', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_number'], ['k.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_k_defendant_aliases_case_number', 'k_defendant_aliases', ['case_number'], unique=False, postgresql_using='hash')
    op.alter_column('dscp_charges', 'victim_age', type_=sa.String)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dscp_charges', 'victim_age', type_=sa.Integer)
    op.drop_index('ixh_k_defendant_aliases_case_number', table_name='k_defendant_aliases', postgresql_using='hash')
    op.drop_table('k_defendant_aliases')
    # ### end Alembic commands ###
