"""Add DV models

Revision ID: 67507d5db7c9
Revises: 26cf16acf1c0
Create Date: 2021-09-11 07:57:17.837327

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '67507d5db7c9'
down_revision = '26cf16acf1c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dv',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('court_system', sa.String(), nullable=True),
    sa.Column('case_type', sa.String(), nullable=True),
    sa.Column('filing_date', sa.Date(), nullable=True),
    sa.Column('filing_date_str', sa.String(), nullable=True),
    sa.Column('case_status', sa.String(), nullable=True),
    sa.Column('order_valid_thru', sa.Date(), nullable=True),
    sa.Column('order_valid_thru_str', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_number'], ['cases.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_number')
    )
    op.create_index('ixh_dv_case_number', 'dv', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('dv_defendants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('DOB', sa.Date(), nullable=True),
    sa.Column('DOB_str', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_number'], ['dv.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_dv_defendants_case_number', 'dv_defendants', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('dv_defendant_attorneys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_number'], ['dv.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_dv_defendant_attorneys_case_number', 'dv_defendant_attorneys', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('dv_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('event_date_str', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_number'], ['dv.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_dv_events_case_number', 'dv_events', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('dv_hearings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hearing_date', sa.Date(), nullable=True),
    sa.Column('hearing_date_str', sa.String(), nullable=True),
    sa.Column('hearing_time', sa.Time(), nullable=True),
    sa.Column('hearing_time_str', sa.String(), nullable=True),
    sa.Column('room', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('served_date', sa.Date(), nullable=True),
    sa.Column('served_date_str', sa.String(), nullable=True),
    sa.Column('hearing_type', sa.String(), nullable=True),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_number'], ['dv.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_dv_hearings_case_number', 'dv_hearings', ['case_number'], unique=False, postgresql_using='hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ixh_dv_hearings_case_number', table_name='dv_hearings', postgresql_using='hash')
    op.drop_table('dv_hearings')
    op.drop_index('ixh_dv_events_case_number', table_name='dv_events', postgresql_using='hash')
    op.drop_table('dv_events')
    op.drop_index('ixh_dv_defendant_attorneys_case_number', table_name='dv_defendant_attorneys', postgresql_using='hash')
    op.drop_table('dv_defendant_attorneys')
    op.drop_index('ixh_dv_defendants_case_number', table_name='dv_defendants', postgresql_using='hash')
    op.drop_table('dv_defendants')
    op.drop_index('ixh_dv_case_number', table_name='dv', postgresql_using='hash')
    op.drop_table('dv')
    # ### end Alembic commands ###
