"""Remove spider-related tables

Revision ID: 7427734c0fc2
Revises: ec14982d61de
Create Date: 2020-04-12 17:08:03.178304

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sys

# revision identifiers, used by Alembic.
revision = '7427734c0fc2'
down_revision = 'ec14982d61de'
branch_labels = None
depends_on = None


def upgrade():
    answer = input('THIS WILL DELETE A LOT OF DATA, ARE YOU SURE? (y/N) ')
    if answer != 'y' and answer != 'Y':
        print("Goodbye!")
        sys.exit(0)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('runs')
    op.drop_table('query_results')
    op.drop_table('queue')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queue',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('search_string', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('court', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('timeouts', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('err500s', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('errunknown', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('site', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='queue_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('query_results',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('search_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('nresults', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('query_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['search_id'], ['queue.id'], name='query_results_search_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='query_results_pkey'),
    sa.UniqueConstraint('search_id', 'timestamp', name='_search_id_timestamp_uc')
    )
    op.create_table('runs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('query_start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('query_end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('court', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('run_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('run_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('queue_still_active', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('queue_finished', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cases_added', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('results_processed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('retry_failed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('site', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='runs_pkey')
    )
    # ### end Alembic commands ###
