"""Add ODYCRIM models

Revision ID: 7a6a54b7b491
Revises: e3c22bdd609b
Create Date: 2019-05-14 17:35:45.225317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a6a54b7b491'
down_revision = 'e3c22bdd609b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('odycrim',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('court_system', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('case_title', sa.String(), nullable=True),
    sa.Column('case_type', sa.String(), nullable=True),
    sa.Column('filing_date', sa.Date(), nullable=True),
    sa.Column('filing_date_str', sa.String(), nullable=True),
    sa.Column('case_status', sa.String(), nullable=True),
    sa.Column('tracking_numbers', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_number'], ['cases.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_odycrim_case_number'), 'odycrim', ['case_number'], unique=True)
    op.create_table('odycrim_bail_bonds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bond_type', sa.String(), nullable=True),
    sa.Column('bond_amount_posted', sa.String(), nullable=True),
    sa.Column('bond_status_date', sa.Date(), nullable=True),
    sa.Column('bond_status_date_str', sa.String(), nullable=True),
    sa.Column('bond_status', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_number'], ['odycrim.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_odycrim_bail_bonds_case_number'), 'odycrim_bail_bonds', ['case_number'], unique=False)
    op.create_table('odycrim_bond_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bail_date', sa.Date(), nullable=True),
    sa.Column('bail_date_str', sa.String(), nullable=True),
    sa.Column('bail_setting_type', sa.String(), nullable=True),
    sa.Column('bail_amount', sa.Numeric(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_number'], ['odycrim.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_odycrim_bond_settings_case_number'), 'odycrim_bond_settings', ['case_number'], unique=False)
    op.create_table('odycrim_charges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('charge_number', sa.Integer(), nullable=True),
    sa.Column('cjis_code', sa.String(), nullable=True),
    sa.Column('statute_code', sa.String(), nullable=True),
    sa.Column('charge_description', sa.String(), nullable=True),
    sa.Column('charge_class', sa.String(), nullable=True),
    sa.Column('probable_cause', sa.Boolean(), nullable=True),
    sa.Column('offense_date_from', sa.Date(), nullable=True),
    sa.Column('offense_date_from_str', sa.String(), nullable=True),
    sa.Column('offense_date_to', sa.Date(), nullable=True),
    sa.Column('offense_date_to_str', sa.String(), nullable=True),
    sa.Column('agency_name', sa.String(), nullable=True),
    sa.Column('officer_id', sa.String(), nullable=True),
    sa.Column('plea', sa.String(), nullable=True),
    sa.Column('plea_date', sa.Date(), nullable=True),
    sa.Column('plea_date_str', sa.String(), nullable=True),
    sa.Column('disposition', sa.String(), nullable=True),
    sa.Column('disposition_date', sa.Date(), nullable=True),
    sa.Column('disposition_date_str', sa.String(), nullable=True),
    sa.Column('converted_disposition', sa.String(), nullable=True),
    sa.Column('jail_life', sa.Boolean(), nullable=True),
    sa.Column('jail_death', sa.Boolean(), nullable=True),
    sa.Column('jail_start_date', sa.Date(), nullable=True),
    sa.Column('jail_start_date_str', sa.String(), nullable=True),
    sa.Column('jail_years', sa.Integer(), nullable=True),
    sa.Column('jail_months', sa.Integer(), nullable=True),
    sa.Column('jail_days', sa.Integer(), nullable=True),
    sa.Column('jail_hours', sa.Integer(), nullable=True),
    sa.Column('jail_suspended_years', sa.Integer(), nullable=True),
    sa.Column('jail_suspended_months', sa.Integer(), nullable=True),
    sa.Column('jail_suspended_days', sa.Integer(), nullable=True),
    sa.Column('jail_suspended_hours', sa.Integer(), nullable=True),
    sa.Column('jail_suspend_all_but_years', sa.Integer(), nullable=True),
    sa.Column('jail_suspend_all_but_months', sa.Integer(), nullable=True),
    sa.Column('jail_suspend_all_but_days', sa.Integer(), nullable=True),
    sa.Column('jail_suspend_all_but_hours', sa.Integer(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_number'], ['odycrim.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_odycrim_charges_case_number'), 'odycrim_charges', ['case_number'], unique=False)
    op.create_table('odycrim_court_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('date_str', sa.String(), nullable=True),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('time_str', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('room', sa.String(), nullable=True),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_number'], ['odycrim.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_odycrim_court_schedule_case_number'), 'odycrim_court_schedule', ['case_number'], unique=False)
    op.create_table('odycrim_defendants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('race', sa.String(), nullable=True),
    sa.Column('sex', sa.String(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('DOB', sa.Date(), nullable=True),
    sa.Column('DOB_str', sa.String(), nullable=True),
    sa.Column('address_1', sa.String(), nullable=True),
    sa.Column('address_2', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('height', sa.String(), nullable=True),
    sa.Column('hair_color', sa.String(), nullable=True),
    sa.Column('eye_color', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_number'], ['odycrim.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_odycrim_defendants_case_number'), 'odycrim_defendants', ['case_number'], unique=False)
    op.create_table('odycrim_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_date', sa.Date(), nullable=True),
    sa.Column('file_date_str', sa.String(), nullable=True),
    sa.Column('filed_by', sa.String(), nullable=True),
    sa.Column('document_name', sa.String(), nullable=False),
    sa.Column('case_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_number'], ['odycrim.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_odycrim_documents_case_number'), 'odycrim_documents', ['case_number'], unique=False)
    op.create_table('odycrim_involved_parties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('party_type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('agency_name', sa.String(), nullable=True),
    sa.Column('address_1', sa.String(), nullable=True),
    sa.Column('address_2', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_number'], ['odycrim.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_odycrim_involved_parties_case_number'), 'odycrim_involved_parties', ['case_number'], unique=False)
    op.create_table('odycrim_probation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('probation_start_date', sa.Date(), nullable=True),
    sa.Column('probation_start_date_str', sa.String(), nullable=True),
    sa.Column('probation_supervised', sa.Boolean(), nullable=True),
    sa.Column('probation_supervised_years', sa.Integer(), nullable=True),
    sa.Column('probation_supervised_months', sa.Integer(), nullable=True),
    sa.Column('probation_supervised_days', sa.Integer(), nullable=True),
    sa.Column('probation_supervised_hours', sa.Integer(), nullable=True),
    sa.Column('probation_usupervised', sa.Boolean(), nullable=True),
    sa.Column('probation_unsupervised_years', sa.Integer(), nullable=True),
    sa.Column('probation_unsupervised_months', sa.Integer(), nullable=True),
    sa.Column('probation_unsupervised_days', sa.Integer(), nullable=True),
    sa.Column('probation_unsupervised_hours', sa.Integer(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_number'], ['odycrim.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_odycrim_probation_case_number'), 'odycrim_probation', ['case_number'], unique=False)
    op.create_table('odycrim_reference_numbers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ref_num', sa.String(), nullable=False),
    sa.Column('ref_num_type', sa.String(), nullable=False),
    sa.Column('case_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_number'], ['odycrim.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_odycrim_reference_numbers_case_number'), 'odycrim_reference_numbers', ['case_number'], unique=False)
    op.create_table('odycrim_restitutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restitution_amount', sa.Numeric(), nullable=True),
    sa.Column('restitution_entered_date', sa.Date(), nullable=True),
    sa.Column('restitution_entered_date_str', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_number'], ['odycrim.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_odycrim_restitutions_case_number'), 'odycrim_restitutions', ['case_number'], unique=False)
    op.create_table('odycrim_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_type', sa.String(), nullable=False),
    sa.Column('issued_date', sa.Date(), nullable=True),
    sa.Column('issued_date_str', sa.String(), nullable=True),
    sa.Column('service_status', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_number'], ['odycrim.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_odycrim_services_case_number'), 'odycrim_services', ['case_number'], unique=False)
    op.create_table('odycrim_warrants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warrant_type', sa.String(), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('issue_date_str', sa.String(), nullable=True),
    sa.Column('last_status', sa.String(), nullable=True),
    sa.Column('status_date', sa.Date(), nullable=True),
    sa.Column('status_date_str', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_number'], ['odycrim.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_odycrim_warrants_case_number'), 'odycrim_warrants', ['case_number'], unique=False)
    op.create_table('odycrim_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(), nullable=False),
    sa.Column('alias_type', sa.String(), nullable=False),
    sa.Column('defendant_id', sa.Integer(), nullable=True),
    sa.Column('party_id', sa.Integer(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_number'], ['odycrim.case_number'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['defendant_id'], ['odycrim_defendants.id'], ),
    sa.ForeignKeyConstraint(['party_id'], ['odycrim_involved_parties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_odycrim_aliases_case_number'), 'odycrim_aliases', ['case_number'], unique=False)
    op.create_table('odycrim_attorneys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address_1', sa.String(), nullable=True),
    sa.Column('address_2', sa.String(), nullable=True),
    sa.Column('address_3', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('defendant_id', sa.Integer(), nullable=True),
    sa.Column('party_id', sa.Integer(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_number'], ['odycrim.case_number'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['defendant_id'], ['odycrim_defendants.id'], ),
    sa.ForeignKeyConstraint(['party_id'], ['odycrim_involved_parties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_odycrim_attorneys_case_number'), 'odycrim_attorneys', ['case_number'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_odycrim_attorneys_case_number'), table_name='odycrim_attorneys')
    op.drop_table('odycrim_attorneys')
    op.drop_index(op.f('ix_odycrim_aliases_case_number'), table_name='odycrim_aliases')
    op.drop_table('odycrim_aliases')
    op.drop_index(op.f('ix_odycrim_warrants_case_number'), table_name='odycrim_warrants')
    op.drop_table('odycrim_warrants')
    op.drop_index(op.f('ix_odycrim_services_case_number'), table_name='odycrim_services')
    op.drop_table('odycrim_services')
    op.drop_index(op.f('ix_odycrim_restitutions_case_number'), table_name='odycrim_restitutions')
    op.drop_table('odycrim_restitutions')
    op.drop_index(op.f('ix_odycrim_reference_numbers_case_number'), table_name='odycrim_reference_numbers')
    op.drop_table('odycrim_reference_numbers')
    op.drop_index(op.f('ix_odycrim_probation_case_number'), table_name='odycrim_probation')
    op.drop_table('odycrim_probation')
    op.drop_index(op.f('ix_odycrim_involved_parties_case_number'), table_name='odycrim_involved_parties')
    op.drop_table('odycrim_involved_parties')
    op.drop_index(op.f('ix_odycrim_documents_case_number'), table_name='odycrim_documents')
    op.drop_table('odycrim_documents')
    op.drop_index(op.f('ix_odycrim_defendants_case_number'), table_name='odycrim_defendants')
    op.drop_table('odycrim_defendants')
    op.drop_index(op.f('ix_odycrim_court_schedule_case_number'), table_name='odycrim_court_schedule')
    op.drop_table('odycrim_court_schedule')
    op.drop_index(op.f('ix_odycrim_charges_case_number'), table_name='odycrim_charges')
    op.drop_table('odycrim_charges')
    op.drop_index(op.f('ix_odycrim_bond_settings_case_number'), table_name='odycrim_bond_settings')
    op.drop_table('odycrim_bond_settings')
    op.drop_index(op.f('ix_odycrim_bail_bonds_case_number'), table_name='odycrim_bail_bonds')
    op.drop_table('odycrim_bail_bonds')
    op.drop_index(op.f('ix_odycrim_case_number'), table_name='odycrim')
    op.drop_table('odycrim')
    # ### end Alembic commands ###
