"""Add indexes to scrapes and scrape_versions tables

Revision ID: 7dba91c1c6c0
Revises: 0ab508b55023
Create Date: 2020-05-07 19:01:38.380489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dba91c1c6c0'
down_revision = '0ab508b55023'
branch_labels = None
depends_on = None


def upgrade():
    op.execute('UPDATE scrapes SET duration = (-duration)')
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_scrapes_versions_case_number_s3_version_id', 'scrape_versions', ['case_number', 's3_version_id'], unique=True)
    op.create_index('ix_scrapes_case_number_s3_version_id', 'scrapes', ['case_number', 's3_version_id'], unique=True)
    op.create_index('ix_scrapes_case_number_timestamp', 'scrapes', ['case_number', sa.text('timestamp DESC')], unique=True)
    op.drop_index('ix_scrape_timestamp', table_name='scrapes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_scrape_timestamp', 'scrapes', ['case_number', 'timestamp'], unique=False)
    op.drop_index('ix_scrapes_case_number_timestamp', table_name='scrapes')
    op.drop_index('ix_scrapes_case_number_s3_version_id', table_name='scrapes')
    op.drop_index('ix_scrapes_versions_case_number_s3_version_id', table_name='scrape_versions')
    # ### end Alembic commands ###

    op.execute('UPDATE scrapes SET duration = (-duration)')
