"""Add satisfied, amended, renewed fields to mccr_judgments

Revision ID: 7ffd37d6c99d
Revises: 8c8e3bfb2073
Create Date: 2021-09-20 07:45:27.050692

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7ffd37d6c99d'
down_revision = '8c8e3bfb2073'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mccr_judgments', sa.Column('satisfied', sa.Date(), nullable=True))
    op.add_column('mccr_judgments', sa.Column('satisfied_str', sa.String(), nullable=True))
    op.add_column('mccr_judgments', sa.Column('amended', sa.Date(), nullable=True))
    op.add_column('mccr_judgments', sa.Column('amended_str', sa.String(), nullable=True))
    op.add_column('mccr_judgments', sa.Column('renewed', sa.Date(), nullable=True))
    op.add_column('mccr_judgments', sa.Column('renewed_str', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mccr_judgments', 'renewed_str')
    op.drop_column('mccr_judgments', 'renewed')
    op.drop_column('mccr_judgments', 'amended_str')
    op.drop_column('mccr_judgments', 'amended')
    op.drop_column('mccr_judgments', 'satisfied_str')
    op.drop_column('mccr_judgments', 'satisfied')
    # ### end Alembic commands ###
