"""Add MCCR models

Revision ID: 8c8e3bfb2073
Revises: 37666ebe1907
Create Date: 2021-09-20 06:57:11.822927

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8c8e3bfb2073'
down_revision = '37666ebe1907'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mccr',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('court_system', sa.String(), nullable=True),
    sa.Column('sub_type', sa.String(), nullable=True),
    sa.Column('filing_date', sa.Date(), nullable=True),
    sa.Column('filing_date_str', sa.String(), nullable=True),
    sa.Column('case_status', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_number'], ['cases.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_number')
    )
    op.create_index('ixh_mccr_case_number', 'mccr', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('mccr_attorneys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('appearance_date', sa.Date(), nullable=True),
    sa.Column('appearance_date_str', sa.String(), nullable=True),
    sa.Column('removal_date', sa.Date(), nullable=True),
    sa.Column('removal_date_str', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_number'], ['mccr.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_mccr_attorneys_case_number', 'mccr_attorneys', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('mccr_bail_bonds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('bond_type', sa.String(), nullable=True),
    sa.Column('amount', sa.Numeric(), nullable=True),
    sa.Column('minimum_percent', sa.Numeric(), nullable=True),
    sa.Column('bond_history', sa.String(), nullable=True),
    sa.Column('bonding_company', sa.String(), nullable=True),
    sa.Column('bonding_company_address', sa.String(), nullable=True),
    sa.Column('agent', sa.String(), nullable=True),
    sa.Column('agent_address', sa.String(), nullable=True),
    sa.Column('remitter', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_number'], ['mccr.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_mccr_bail_bonds_case_number', 'mccr_bail_bonds', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('mccr_charges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('charge_number', sa.String(), nullable=True),
    sa.Column('expunged', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('article_section_subsection', sa.String(), nullable=True),
    sa.Column('charge_description', sa.String(), nullable=True),
    sa.Column('citation_number', sa.String(), nullable=True),
    sa.Column('plea', sa.String(), nullable=True),
    sa.Column('disposition_text', sa.String(), nullable=True),
    sa.Column('disposition_date', sa.Date(), nullable=True),
    sa.Column('disposition_date_str', sa.String(), nullable=True),
    sa.Column('disposition', sa.String(), nullable=True),
    sa.Column('judge', sa.String(), nullable=True),
    sa.Column('imposed_life_times', sa.String(), nullable=True),
    sa.Column('imposed_years', sa.Integer(), nullable=True),
    sa.Column('imposed_months', sa.Integer(), nullable=True),
    sa.Column('imposed_days', sa.Integer(), nullable=True),
    sa.Column('imposed_consecutive', sa.Boolean(), nullable=True),
    sa.Column('imposed_concurrent', sa.Boolean(), nullable=True),
    sa.Column('time_served_years', sa.Integer(), nullable=True),
    sa.Column('time_served_months', sa.Integer(), nullable=True),
    sa.Column('time_served_days', sa.Integer(), nullable=True),
    sa.Column('time_suspended_all_but', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('time_suspended_years', sa.Integer(), nullable=True),
    sa.Column('time_suspended_months', sa.Integer(), nullable=True),
    sa.Column('time_suspended_days', sa.Integer(), nullable=True),
    sa.Column('probation_supervised', sa.Boolean(), nullable=True),
    sa.Column('probation_unsupervised', sa.Boolean(), nullable=True),
    sa.Column('probation_years', sa.Integer(), nullable=True),
    sa.Column('probation_months', sa.Integer(), nullable=True),
    sa.Column('probation_days', sa.Integer(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_number'], ['mccr.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_mccr_charges_case_number', 'mccr_charges', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('mccr_court_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('event_date_str', sa.String(), nullable=True),
    sa.Column('event_time', sa.Time(), nullable=True),
    sa.Column('event_time_str', sa.String(), nullable=True),
    sa.Column('judge', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('courtroom', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_number'], ['mccr.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_mccr_court_schedule_case_number', 'mccr_court_schedule', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('mccr_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alias_name', sa.String(), nullable=True),
    sa.Column('party', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_number'], ['mccr.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_mccr_aliases_case_number', 'mccr_aliases', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('mccr_defendants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('DOB', sa.Date(), nullable=True),
    sa.Column('DOB_str', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_number'], ['mccr.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_mccr_defendants_case_number', 'mccr_defendants', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('mccr_district_court_numbers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('district_court_number', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_number'], ['mccr.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_mccr_district_court_numbers_case_number', 'mccr_district_court_numbers', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('mccr_dockets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('docket_date', sa.Date(), nullable=True),
    sa.Column('docket_date_str', sa.String(), nullable=True),
    sa.Column('docket_number', sa.Integer(), nullable=True),
    sa.Column('docket_description', sa.String(), nullable=True),
    sa.Column('docket_type', sa.String(), nullable=True),
    sa.Column('filed_by', sa.String(), nullable=True),
    sa.Column('docket_text', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_number'], ['mccr.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_mccr_dockets_case_number', 'mccr_dockets', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('mccr_dwi_monitors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_number'], ['mccr.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_mccr_dwi_monitors_case_number', 'mccr_dwi_monitors', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('mccr_judgments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('date_str', sa.String(), nullable=True),
    sa.Column('amount', sa.Numeric(), nullable=True),
    sa.Column('entered_date', sa.Date(), nullable=True),
    sa.Column('entered_date_str', sa.String(), nullable=True),
    sa.Column('vacated_date', sa.Date(), nullable=True),
    sa.Column('vacated_date_str', sa.String(), nullable=True),
    sa.Column('debtor', sa.String(), nullable=True),
    sa.Column('party_role', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_number'], ['mccr.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_mccr_judgments_case_number', 'mccr_judgments', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('mccr_probation_officers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_number'], ['mccr.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_mccr_probation_officers_case_number', 'mccr_probation_officers', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('mccr_tracking_numbers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tracking_number', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_number'], ['mccr.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_mccr_tracking_numbers_case_number', 'mccr_tracking_numbers', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('mccr_audio_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audio_media', sa.String(), nullable=True),
    sa.Column('audio_start', sa.String(), nullable=True),
    sa.Column('audio_stop', sa.String(), nullable=True),
    sa.Column('docket_id', sa.Integer(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_number'], ['mccr.case_number'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['docket_id'], ['mccr_dockets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_mccr_audio_media_case_number', 'mccr_audio_media', ['case_number'], unique=False, postgresql_using='hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ixh_mccr_audio_media_case_number', table_name='mccr_audio_media', postgresql_using='hash')
    op.drop_table('mccr_audio_media')
    op.drop_index('ixh_mccr_tracking_numbers_case_number', table_name='mccr_tracking_numbers', postgresql_using='hash')
    op.drop_table('mccr_tracking_numbers')
    op.drop_index('ixh_mccr_probation_officers_case_number', table_name='mccr_probation_officers', postgresql_using='hash')
    op.drop_table('mccr_probation_officers')
    op.drop_index('ixh_mccr_judgments_case_number', table_name='mccr_judgments', postgresql_using='hash')
    op.drop_table('mccr_judgments')
    op.drop_index('ixh_mccr_dwi_monitors_case_number', table_name='mccr_dwi_monitors', postgresql_using='hash')
    op.drop_table('mccr_dwi_monitors')
    op.drop_index('ixh_mccr_dockets_case_number', table_name='mccr_dockets', postgresql_using='hash')
    op.drop_table('mccr_dockets')
    op.drop_index('ixh_mccr_district_court_numbers_case_number', table_name='mccr_district_court_numbers', postgresql_using='hash')
    op.drop_table('mccr_district_court_numbers')
    op.drop_index('ixh_mccr_defendants_case_number', table_name='mccr_defendants', postgresql_using='hash')
    op.drop_table('mccr_defendants')
    op.drop_index('ixh_mccr_aliases_case_number', table_name='mccr_aliases', postgresql_using='hash')
    op.drop_table('mccr_aliases')
    op.drop_index('ixh_mccr_court_schedule_case_number', table_name='mccr_court_schedule', postgresql_using='hash')
    op.drop_table('mccr_court_schedule')
    op.drop_index('ixh_mccr_charges_case_number', table_name='mccr_charges', postgresql_using='hash')
    op.drop_table('mccr_charges')
    op.drop_index('ixh_mccr_bail_bonds_case_number', table_name='mccr_bail_bonds', postgresql_using='hash')
    op.drop_table('mccr_bail_bonds')
    op.drop_index('ixh_mccr_attorneys_case_number', table_name='mccr_attorneys', postgresql_using='hash')
    op.drop_table('mccr_attorneys')
    op.drop_index('ixh_mccr_case_number', table_name='mccr', postgresql_using='hash')
    op.drop_table('mccr')
    # ### end Alembic commands ###
