"""Fix incorrect data type for totalprincipal

Revision ID: 8fada70ffb2b
Revises: 0be25bbbbd8c
Create Date: 2021-03-01 17:34:16.997199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fada70ffb2b'
down_revision = '0be25bbbbd8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('odycivil_judgment_comments', 'totalprincipal', type_=sa.String)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('odycivil_judgment_comments', 'totalprincipal', type_=sa.Numeric)
    # ### end Alembic commands ###
