"""Typo in odycrim_probation column

Revision ID: 950f3ef6e583
Revises: bf65425d1227
Create Date: 2019-08-27 13:47:48.576321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '950f3ef6e583'
down_revision = 'bf65425d1227'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('odycrim_probation','probation_usupervised',new_column_name='probation_unsupervised')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('odycrim_probation','probation_unsupervised',new_column_name='probation_usupervised')
    # ### end Alembic commands ###
