"""Add disposition_merged_text to k_charges

Revision ID: 98327ab2ad75
Revises: cd14501526dc
Create Date: 2021-08-23 08:16:27.022116

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '98327ab2ad75'
down_revision = 'cd14501526dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('k_charges', sa.Column('disposition_merged_text', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('k_charges', 'disposition_merged_text')
    # ### end Alembic commands ###
