"""Add address_3 to k_party_addresses

Revision ID: 987da5298aca
Revises: 10a283d18aa0
Create Date: 2021-09-01 13:56:09.501879

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '987da5298aca'
down_revision = '10a283d18aa0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('k_party_addresses', sa.Column('address_3', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('k_party_addresses', 'address_3')
    # ### end Alembic commands ###
