"""Refactor ODYTRAF models

Revision ID: 9d335febaed3
Revises: 7a6a54b7b491
Create Date: 2019-05-15 17:53:38.661581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d335febaed3'
down_revision = '7a6a54b7b491'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('odytraf_involved_parties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('party_type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('agency_name', sa.String(), nullable=True),
    sa.Column('address_1', sa.String(), nullable=True),
    sa.Column('address_2', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_number'], ['odytraf.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_odytraf_involved_parties_case_number'), 'odytraf_involved_parties', ['case_number'], unique=False)
    op.add_column('odytraf_aliases', sa.Column('party_id', sa.Integer(), nullable=True))
    op.drop_constraint('odytraf_aliases_surety_id_fkey', 'odytraf_aliases', type_='foreignkey')
    op.drop_constraint('odytraf_aliases_interpreter_id_fkey', 'odytraf_aliases', type_='foreignkey')
    op.drop_constraint('odytraf_aliases_probation_officer_id_fkey', 'odytraf_aliases', type_='foreignkey')
    op.drop_constraint('odytraf_aliases_bondsman_id_fkey', 'odytraf_aliases', type_='foreignkey')
    op.create_foreign_key('odytraf_aliases_involved_parties_id_fkey', 'odytraf_aliases', 'odytraf_involved_parties', ['party_id'], ['id'])
    op.drop_column('odytraf_aliases', 'probation_officer_id')
    op.drop_column('odytraf_aliases', 'bondsman_id')
    op.drop_column('odytraf_aliases', 'surety_id')
    op.drop_column('odytraf_aliases', 'interpreter_id')
    op.add_column('odytraf_attorneys', sa.Column('party_id', sa.Integer(), nullable=True))
    op.drop_constraint('odytraf_attorneys_plaintiff_id_fkey', 'odytraf_attorneys', type_='foreignkey')
    op.create_foreign_key('odytraf_attorneys_involved_parties_id_fkey', 'odytraf_attorneys', 'odytraf_involved_parties', ['party_id'], ['id'])
    op.drop_column('odytraf_attorneys', 'plaintiff_id')
    op.drop_index('ix_odytraf_interpreters_case_number', table_name='odytraf_interpreters')
    op.drop_table('odytraf_interpreters')
    op.drop_index('ix_odytraf_sureties_case_number', table_name='odytraf_sureties')
    op.drop_table('odytraf_sureties')
    op.drop_index('ix_odytraf_bondsmen_case_number', table_name='odytraf_bondsmen')
    op.drop_table('odytraf_bondsmen')
    op.drop_index('ix_odytraf_plaintiffs_case_number', table_name='odytraf_plaintiffs')
    op.drop_table('odytraf_plaintiffs')
    op.drop_index('ix_odytraf_officers_case_number', table_name='odytraf_officers')
    op.drop_table('odytraf_officers')
    op.drop_index('ix_odytraf_probation_officers_case_number', table_name='odytraf_probation_officers')
    op.drop_table('odytraf_probation_officers')
    op.execute('UPDATE cases SET last_parse = NULL WHERE detail_loc = \'ODYTRAF\' AND last_parse IS NOT NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('odytraf_attorneys', sa.Column('plaintiff_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint('odytraf_attorneys_involved_parties_id_fkey', 'odytraf_attorneys', type_='foreignkey')
    op.create_foreign_key('odytraf_attorneys_plaintiff_id_fkey', 'odytraf_attorneys', 'odytraf_plaintiffs', ['plaintiff_id'], ['id'])
    op.drop_column('odytraf_attorneys', 'party_id')
    op.add_column('odytraf_aliases', sa.Column('interpreter_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('odytraf_aliases', sa.Column('surety_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('odytraf_aliases', sa.Column('bondsman_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('odytraf_aliases', sa.Column('probation_officer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint('odytraf_aliases_involved_parties_id_fkey', 'odytraf_aliases', type_='foreignkey')
    op.create_foreign_key('odytraf_aliases_bondsman_id_fkey', 'odytraf_aliases', 'odytraf_defendants', ['bondsman_id'], ['id'])
    op.create_foreign_key('odytraf_aliases_probation_officer_id_fkey', 'odytraf_aliases', 'odytraf_defendants', ['probation_officer_id'], ['id'])
    op.create_foreign_key('odytraf_aliases_interpreter_id_fkey', 'odytraf_aliases', 'odytraf_defendants', ['interpreter_id'], ['id'])
    op.create_foreign_key('odytraf_aliases_surety_id_fkey', 'odytraf_aliases', 'odytraf_defendants', ['surety_id'], ['id'])
    op.drop_column('odytraf_aliases', 'party_id')
    op.create_table('odytraf_probation_officers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('zip_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('case_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address_1', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address_2', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['case_number'], ['odytraf.case_number'], name='odytraf_probation_officers_case_number_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='odytraf_probation_officers_pkey')
    )
    op.create_index('ix_odytraf_probation_officers_case_number', 'odytraf_probation_officers', ['case_number'], unique=False)
    op.create_table('odytraf_officers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('agency_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('address_1', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address_2', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('zip_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('case_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['case_number'], ['odytraf.case_number'], name='odytraf_officers_case_number_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='odytraf_officers_pkey')
    )
    op.create_index('ix_odytraf_officers_case_number', 'odytraf_officers', ['case_number'], unique=False)
    op.create_table('odytraf_plaintiffs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('case_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['case_number'], ['odytraf.case_number'], name='odytraf_plaintiffs_case_number_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='odytraf_plaintiffs_pkey')
    )
    op.create_index('ix_odytraf_plaintiffs_case_number', 'odytraf_plaintiffs', ['case_number'], unique=False)
    op.create_table('odytraf_bondsmen',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('zip_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('case_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address_1', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address_2', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['case_number'], ['odytraf.case_number'], name='odytraf_bondsmen_case_number_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='odytraf_bondsmen_pkey')
    )
    op.create_index('ix_odytraf_bondsmen_case_number', 'odytraf_bondsmen', ['case_number'], unique=False)
    op.create_table('odytraf_sureties',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('zip_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('case_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address_1', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address_2', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['case_number'], ['odytraf.case_number'], name='odytraf_sureties_case_number_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='odytraf_sureties_pkey')
    )
    op.create_index('ix_odytraf_sureties_case_number', 'odytraf_sureties', ['case_number'], unique=False)
    op.create_table('odytraf_interpreters',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('zip_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('case_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address_1', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address_2', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['case_number'], ['odytraf.case_number'], name='odytraf_interpreters_case_number_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='odytraf_interpreters_pkey')
    )
    op.create_index('ix_odytraf_interpreters_case_number', 'odytraf_interpreters', ['case_number'], unique=False)
    op.drop_index(op.f('ix_odytraf_involved_parties_case_number'), table_name='odytraf_involved_parties')
    op.drop_table('odytraf_involved_parties')
    # ### end Alembic commands ###
