"""Modified k_charges

Revision ID: 9dbb2931da09
Revises: 66e022919043
Create Date: 2021-08-23 06:34:54.284876

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9dbb2931da09'
down_revision = '66e022919043'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('k_charges', sa.Column('jail_unsuspended_years', sa.Integer(), nullable=True))
    op.add_column('k_charges', sa.Column('jail_unsuspended_months', sa.Integer(), nullable=True))
    op.add_column('k_charges', sa.Column('jail_unsuspended_days', sa.Integer(), nullable=True))
    op.add_column('k_charges', sa.Column('jail_unsuspended_hours', sa.Integer(), nullable=True))
    op.drop_column('k_charges', 'jail_suspend_all_but_months')
    op.drop_column('k_charges', 'jail_suspend_all_but_years')
    op.drop_column('k_charges', 'jail_suspend_all_but_days')
    op.drop_column('k_charges', 'jail_suspend_all_but_hours')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('k_charges', sa.Column('jail_suspend_all_but_hours', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('k_charges', sa.Column('jail_suspend_all_but_days', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('k_charges', sa.Column('jail_suspend_all_but_years', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('k_charges', sa.Column('jail_suspend_all_but_months', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('k_charges', 'jail_unsuspended_hours')
    op.drop_column('k_charges', 'jail_unsuspended_days')
    op.drop_column('k_charges', 'jail_unsuspended_months')
    op.drop_column('k_charges', 'jail_unsuspended_years')
    # ### end Alembic commands ###
