"""Additional fields for odycivil_judgment_comments

Revision ID: a6437e172d13
Revises: 8fada70ffb2b
Create Date: 2021-03-02 11:35:55.848812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6437e172d13'
down_revision = '8fada70ffb2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('odycivil_judgment_comments', sa.Column('renewed_date', sa.Date(), nullable=True))
    op.add_column('odycivil_judgment_comments', sa.Column('renewed_date_end_str', sa.String(), nullable=True))
    op.add_column('odycivil_judgment_comments', sa.Column('renewed_date_ent', sa.Date(), nullable=True))
    op.add_column('odycivil_judgment_comments', sa.Column('renewed_date_str', sa.String(), nullable=True))
    op.add_column('odycivil_judgment_comments', sa.Column('renewed_lien_date', sa.Date(), nullable=True))
    op.add_column('odycivil_judgment_comments', sa.Column('renewed_lien_date_str', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('odycivil_judgment_comments', 'renewed_lien_date_str')
    op.drop_column('odycivil_judgment_comments', 'renewed_lien_date')
    op.drop_column('odycivil_judgment_comments', 'renewed_date_str')
    op.drop_column('odycivil_judgment_comments', 'renewed_date_ent')
    op.drop_column('odycivil_judgment_comments', 'renewed_date_end_str')
    op.drop_column('odycivil_judgment_comments', 'renewed_date')
    # ### end Alembic commands ###
