"""Remove unused field in CC

Revision ID: a68a233d6b44
Revises: 0529952f8a2b
Create Date: 2021-10-12 08:48:32.384913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a68a233d6b44'
down_revision = '0529952f8a2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cc_documents', 'sequence_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cc_documents', sa.Column('sequence_number', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
