"""Added jail fields to ODYCVCITCharge

Revision ID: aaa83181c4a5
Revises: ba65d4f0e491
Create Date: 2021-07-13 17:07:46.459076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaa83181c4a5'
down_revision = 'ba65d4f0e491'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('odycvcit_charges', sa.Column('converted_disposition', sa.String(), nullable=True))
    op.add_column('odycvcit_charges', sa.Column('jail_life', sa.Boolean(), nullable=True))
    op.add_column('odycvcit_charges', sa.Column('jail_death', sa.Boolean(), nullable=True))
    op.add_column('odycvcit_charges', sa.Column('jail_start_date', sa.Date(), nullable=True))
    op.add_column('odycvcit_charges', sa.Column('jail_start_date_str', sa.String(), nullable=True))
    op.add_column('odycvcit_charges', sa.Column('jail_cons_conc', sa.String(), nullable=True))
    op.add_column('odycvcit_charges', sa.Column('jail_years', sa.Integer(), nullable=True))
    op.add_column('odycvcit_charges', sa.Column('jail_months', sa.Integer(), nullable=True))
    op.add_column('odycvcit_charges', sa.Column('jail_days', sa.Integer(), nullable=True))
    op.add_column('odycvcit_charges', sa.Column('jail_hours', sa.Integer(), nullable=True))
    op.add_column('odycvcit_charges', sa.Column('jail_suspended_term', sa.String(), nullable=True))
    op.add_column('odycvcit_charges', sa.Column('jail_suspended_years', sa.Integer(), nullable=True))
    op.add_column('odycvcit_charges', sa.Column('jail_suspended_months', sa.Integer(), nullable=True))
    op.add_column('odycvcit_charges', sa.Column('jail_suspended_days', sa.Integer(), nullable=True))
    op.add_column('odycvcit_charges', sa.Column('jail_suspended_hours', sa.Integer(), nullable=True))
    op.add_column('odycvcit_charges', sa.Column('jail_suspend_all_but_years', sa.Integer(), nullable=True))
    op.add_column('odycvcit_charges', sa.Column('jail_suspend_all_but_months', sa.Integer(), nullable=True))
    op.add_column('odycvcit_charges', sa.Column('jail_suspend_all_but_days', sa.Integer(), nullable=True))
    op.add_column('odycvcit_charges', sa.Column('jail_suspend_all_but_hours', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('odycvcit_charges', 'jail_suspend_all_but_hours')
    op.drop_column('odycvcit_charges', 'jail_suspend_all_but_days')
    op.drop_column('odycvcit_charges', 'jail_suspend_all_but_months')
    op.drop_column('odycvcit_charges', 'jail_suspend_all_but_years')
    op.drop_column('odycvcit_charges', 'jail_suspended_hours')
    op.drop_column('odycvcit_charges', 'jail_suspended_days')
    op.drop_column('odycvcit_charges', 'jail_suspended_months')
    op.drop_column('odycvcit_charges', 'jail_suspended_years')
    op.drop_column('odycvcit_charges', 'jail_suspended_term')
    op.drop_column('odycvcit_charges', 'jail_hours')
    op.drop_column('odycvcit_charges', 'jail_days')
    op.drop_column('odycvcit_charges', 'jail_months')
    op.drop_column('odycvcit_charges', 'jail_years')
    op.drop_column('odycvcit_charges', 'jail_cons_conc')
    op.drop_column('odycvcit_charges', 'jail_start_date_str')
    op.drop_column('odycvcit_charges', 'jail_start_date')
    op.drop_column('odycvcit_charges', 'jail_death')
    op.drop_column('odycvcit_charges', 'jail_life')
    op.drop_column('odycvcit_charges', 'converted_disposition')
    # ### end Alembic commands ###
