"""Add probation and jail fields to ODYTRAF charge table

Revision ID: ad575f796294
Revises: d66528af89f3
Create Date: 2019-04-11 16:43:44.172681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad575f796294'
down_revision = 'd66528af89f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('odytraf_charges', sa.Column('jail_days', sa.Integer(), nullable=True))
    op.add_column('odytraf_charges', sa.Column('jail_hours', sa.Integer(), nullable=True))
    op.add_column('odytraf_charges', sa.Column('jail_life_death', sa.String(), nullable=True))
    op.add_column('odytraf_charges', sa.Column('jail_months', sa.Integer(), nullable=True))
    op.add_column('odytraf_charges', sa.Column('jail_start_date', sa.Date(), nullable=True))
    op.add_column('odytraf_charges', sa.Column('jail_start_date_str', sa.String(), nullable=True))
    op.add_column('odytraf_charges', sa.Column('jail_suspended_days', sa.Integer(), nullable=True))
    op.add_column('odytraf_charges', sa.Column('jail_suspended_hours', sa.Integer(), nullable=True))
    op.add_column('odytraf_charges', sa.Column('jail_suspended_months', sa.Integer(), nullable=True))
    op.add_column('odytraf_charges', sa.Column('jail_suspended_years', sa.Integer(), nullable=True))
    op.add_column('odytraf_charges', sa.Column('jail_suspend_all_but_days', sa.Integer(), nullable=True))
    op.add_column('odytraf_charges', sa.Column('jail_suspend_all_but_hours', sa.Integer(), nullable=True))
    op.add_column('odytraf_charges', sa.Column('jail_suspend_all_but_months', sa.Integer(), nullable=True))
    op.add_column('odytraf_charges', sa.Column('jail_suspend_all_but_years', sa.Integer(), nullable=True))
    op.add_column('odytraf_charges', sa.Column('jail_years', sa.Integer(), nullable=True))
    op.add_column('odytraf_charges', sa.Column('probation_start_date', sa.Date(), nullable=True))
    op.add_column('odytraf_charges', sa.Column('probation_start_date_str', sa.String(), nullable=True))
    op.add_column('odytraf_charges', sa.Column('probation_supervised_days', sa.Integer(), nullable=True))
    op.add_column('odytraf_charges', sa.Column('probation_supervised_hours', sa.Integer(), nullable=True))
    op.add_column('odytraf_charges', sa.Column('probation_supervised_months', sa.Integer(), nullable=True))
    op.add_column('odytraf_charges', sa.Column('probation_supervised_years', sa.Integer(), nullable=True))
    op.add_column('odytraf_charges', sa.Column('probation_unsupervised_days', sa.Integer(), nullable=True))
    op.add_column('odytraf_charges', sa.Column('probation_unsupervised_hours', sa.Integer(), nullable=True))
    op.add_column('odytraf_charges', sa.Column('probation_unsupervised_months', sa.Integer(), nullable=True))
    op.add_column('odytraf_charges', sa.Column('probation_unsupervised_years', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('odytraf_charges', 'probation_unsupervised_years')
    op.drop_column('odytraf_charges', 'probation_unsupervised_months')
    op.drop_column('odytraf_charges', 'probation_unsupervised_hours')
    op.drop_column('odytraf_charges', 'probation_unsupervised_days')
    op.drop_column('odytraf_charges', 'probation_supervised_years')
    op.drop_column('odytraf_charges', 'probation_supervised_months')
    op.drop_column('odytraf_charges', 'probation_supervised_hours')
    op.drop_column('odytraf_charges', 'probation_supervised_days')
    op.drop_column('odytraf_charges', 'probation_start_date_str')
    op.drop_column('odytraf_charges', 'probation_start_date')
    op.drop_column('odytraf_charges', 'jail_years')
    op.drop_column('odytraf_charges', 'jail_suspend_all_but_years')
    op.drop_column('odytraf_charges', 'jail_suspend_all_but_months')
    op.drop_column('odytraf_charges', 'jail_suspend_all_but_hours')
    op.drop_column('odytraf_charges', 'jail_suspend_all_but_days')
    op.drop_column('odytraf_charges', 'jail_suspended_years')
    op.drop_column('odytraf_charges', 'jail_suspended_months')
    op.drop_column('odytraf_charges', 'jail_suspended_hours')
    op.drop_column('odytraf_charges', 'jail_suspended_days')
    op.drop_column('odytraf_charges', 'jail_start_date_str')
    op.drop_column('odytraf_charges', 'jail_start_date')
    op.drop_column('odytraf_charges', 'jail_months')
    op.drop_column('odytraf_charges', 'jail_life_death')
    op.drop_column('odytraf_charges', 'jail_hours')
    op.drop_column('odytraf_charges', 'jail_days')
    # ### end Alembic commands ###
