"""Missing fields

Revision ID: aed623153eb1
Revises: aaa83181c4a5
Create Date: 2021-07-14 17:16:42.906620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aed623153eb1'
down_revision = 'aaa83181c4a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('odycivil_judgment_comments', sa.Column('val_of_prop_to', sa.String(), nullable=True))
    op.add_column('odycivil_judgments', sa.Column('interest_rate_details', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('odycivil_judgments', 'interest_rate_details')
    op.drop_column('odycivil_judgment_comments', 'val_of_prop_to')
    # ### end Alembic commands ###
