"""Add error field to scrapes table and add server-side defaults for boolean fields

Revision ID: b016102d2c6a
Revises: 4baf21cf0e43
Create Date: 2020-07-09 14:03:56.174294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b016102d2c6a'
down_revision = '4baf21cf0e43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cases', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               server_default='true')
    op.alter_column('cases', 'parse_exempt',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               server_default='false')
    op.alter_column('cases', 'scrape_exempt',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               server_default='false')
    op.add_column('scrapes', sa.Column('error', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scrapes', 'error')
    op.alter_column('cases', 'scrape_exempt',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('cases', 'parse_exempt',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('cases', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
