"""Added trial_judgment_against_plaintiff to odycivil_judgments

Revision ID: b1203592827f
Revises: 0d1827f56503
Create Date: 2021-07-25 09:14:11.535709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1203592827f'
down_revision = '0d1827f56503'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('odycivil_judgments', sa.Column('trial_judgment_against_plaintiff', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('odycivil_judgments', 'trial_judgment_against_plaintiff')
    # ### end Alembic commands ###
