"""Add order to column_metadata

Revision ID: b1570fa6c264
Revises: 003e6ae1f9b5
Create Date: 2021-08-13 12:34:05.701075

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b1570fa6c264'
down_revision = '003e6ae1f9b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('column_metadata', sa.Column('order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('column_metadata', 'order')
    # ### end Alembic commands ###
