"""Remove unused fields in ODYCRIM

Revision ID: b4f7a1413269
Revises: 04256934a246
Create Date: 2021-10-11 15:16:05.739117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4f7a1413269'
down_revision = '04256934a246'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('odycrim_documents', 'filed_by')
    op.drop_column('odycrim_involved_parties', 'removal_date_str')
    op.drop_column('odycrim_involved_parties', 'appearance_date')
    op.drop_column('odycrim_involved_parties', 'appearance_date_str')
    op.drop_column('odycrim_involved_parties', 'removal_date')
    op.drop_column('odycrim_services', 'service_status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('odycrim_services', sa.Column('service_status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('odycrim_involved_parties', sa.Column('removal_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('odycrim_involved_parties', sa.Column('appearance_date_str', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('odycrim_involved_parties', sa.Column('appearance_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('odycrim_involved_parties', sa.Column('removal_date_str', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('odycrim_documents', sa.Column('filed_by', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
