"""Rename ODYCVCIT_documents

Revision ID: b8eb352e4f9e
Revises: ed5fea32af69
Create Date: 2021-08-04 09:42:16.643979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8eb352e4f9e'
down_revision = 'ed5fea32af69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('ODYCVCIT_documents', 'odycvcit_documents')
    op.execute('ALTER INDEX "ixh_ODYCVCIT_documents_case_number" RENAME TO ixh_odycvcit_documents_case_number')
    op.execute('ALTER INDEX "ODYCVCIT_documents_pkey" RENAME TO odycvcit_documents_pkey')
    op.execute('ALTER TABLE odycvcit_documents RENAME CONSTRAINT "ODYCVCIT_documents_case_number_fkey" TO odycvcit_documents_case_number_fkey')
    op.execute('ALTER SEQUENCE "ODYCVCIT_documents_id_seq" RENAME TO odycvcit_documents_id_seq')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER SEQUENCE odycvcit_documents_id_seq RENAME TO "ODYCVCIT_documents_id_seq"')
    op.execute('ALTER TABLE odycvcit_documents RENAME CONSTRAINT odycvcit_documents_case_number_fkey TO "ODYCVCIT_documents_case_number_fkey"')
    op.execute('ALTER INDEX odycvcit_documents_pkey RENAME TO "ODYCVCIT_documents_pkey"')
    op.execute('ALTER INDEX ixh_odycvcit_documents_case_number RENAME TO "ixh_ODYCVCIT_documents_case_number"')
    op.rename_table('odycvcit_documents', 'ODYCVCIT_documents')
    # ### end Alembic commands ###
