"""Added ODYCVCIT models

Revision ID: ba65d4f0e491
Revises: 633f3939b99d
Create Date: 2021-07-12 12:29:07.186854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba65d4f0e491'
down_revision = '03d75d982909'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('odycvcit_charges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.Column('charge_number', sa.Integer(), nullable=True),
    sa.Column('possibly_expunged', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('cjis_code', sa.String(), nullable=True),
    sa.Column('statute_code', sa.String(), nullable=True),
    sa.Column('charge_description', sa.String(), nullable=True),
    sa.Column('charge_class', sa.String(), nullable=True),
    sa.Column('probable_cause', sa.Boolean(), nullable=True),
    sa.Column('offense_date_from', sa.Date(), nullable=True),
    sa.Column('offense_date_from_str', sa.String(), nullable=True),
    sa.Column('offense_date_to', sa.Date(), nullable=True),
    sa.Column('offense_date_to_str', sa.String(), nullable=True),
    sa.Column('agency_name', sa.String(), nullable=True),
    sa.Column('officer_id', sa.String(), nullable=True),
    sa.Column('plea', sa.String(), nullable=True),
    sa.Column('plea_date', sa.Date(), nullable=True),
    sa.Column('plea_date_str', sa.String(), nullable=True),
    sa.Column('disposition', sa.String(), nullable=True),
    sa.Column('disposition_date', sa.Date(), nullable=True),
    sa.Column('disposition_date_str', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_odycvcit_charges_case_number', 'odycvcit_charges', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('odycvcit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('court_system', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('case_title', sa.String(), nullable=True),
    sa.Column('case_type', sa.String(), nullable=True),
    sa.Column('filing_date', sa.Date(), nullable=True),
    sa.Column('filing_date_str', sa.String(), nullable=True),
    sa.Column('case_status', sa.String(), nullable=True),
    sa.Column('tracking_numbers', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_number'], ['cases.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_number')
    )
    op.create_index('ixh_odycvcit_case_number', 'odycvcit', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('ODYCVCIT_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_date', sa.Date(), nullable=True),
    sa.Column('file_date_str', sa.String(), nullable=True),
    sa.Column('filed_by', sa.String(), nullable=True),
    sa.Column('document_name', sa.String(), nullable=False),
    sa.Column('case_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_number'], ['odycvcit.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_ODYCVCIT_documents_case_number', 'ODYCVCIT_documents', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('odycvcit_bail_bonds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bond_type', sa.String(), nullable=True),
    sa.Column('bond_amount_posted', sa.String(), nullable=True),
    sa.Column('bond_status_date', sa.Date(), nullable=True),
    sa.Column('bond_status_date_str', sa.String(), nullable=True),
    sa.Column('bond_status', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_number'], ['odycvcit.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_odycvcit_bail_bonds_case_number', 'odycvcit_bail_bonds', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('odycvcit_bond_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bail_date', sa.Date(), nullable=True),
    sa.Column('bail_date_str', sa.String(), nullable=True),
    sa.Column('bail_setting_type', sa.String(), nullable=True),
    sa.Column('bail_amount', sa.Numeric(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_number'], ['odycvcit.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_odycvcit_bond_settings_case_number', 'odycvcit_bond_settings', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('odycvcit_court_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('date_str', sa.String(), nullable=True),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('time_str', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('room', sa.String(), nullable=True),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_number'], ['odycvcit.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_odycvcit_court_schedule_case_number', 'odycvcit_court_schedule', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('odycvcit_defendants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('race', sa.String(), nullable=True),
    sa.Column('sex', sa.String(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('DOB', sa.Date(), nullable=True),
    sa.Column('DOB_str', sa.String(), nullable=True),
    sa.Column('address_1', sa.String(), nullable=True),
    sa.Column('address_2', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('height', sa.String(), nullable=True),
    sa.Column('hair_color', sa.String(), nullable=True),
    sa.Column('eye_color', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_number'], ['odycvcit.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_odycvcit_defendants_case_number', 'odycvcit_defendants', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('odycvcit_involved_parties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('party_type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('appearance_date', sa.Date(), nullable=True),
    sa.Column('appearance_date_str', sa.String(), nullable=True),
    sa.Column('removal_date', sa.Date(), nullable=True),
    sa.Column('removal_date_str', sa.String(), nullable=True),
    sa.Column('agency_name', sa.String(), nullable=True),
    sa.Column('address_1', sa.String(), nullable=True),
    sa.Column('address_2', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_number'], ['odycvcit.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_odycvcit_involved_parties_case_number', 'odycvcit_involved_parties', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('odycvcit_probation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('probation_start_date', sa.Date(), nullable=True),
    sa.Column('probation_start_date_str', sa.String(), nullable=True),
    sa.Column('probation_supervised', sa.Boolean(), nullable=True),
    sa.Column('probation_supervised_years', sa.Integer(), nullable=True),
    sa.Column('probation_supervised_months', sa.Integer(), nullable=True),
    sa.Column('probation_supervised_days', sa.Integer(), nullable=True),
    sa.Column('probation_supervised_hours', sa.Integer(), nullable=True),
    sa.Column('probation_unsupervised', sa.Boolean(), nullable=True),
    sa.Column('probation_unsupervised_years', sa.Integer(), nullable=True),
    sa.Column('probation_unsupervised_months', sa.Integer(), nullable=True),
    sa.Column('probation_unsupervised_days', sa.Integer(), nullable=True),
    sa.Column('probation_unsupervised_hours', sa.Integer(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_number'], ['odycvcit.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_odycvcit_probation_case_number', 'odycvcit_probation', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('odycvcit_reference_numbers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ref_num', sa.String(), nullable=False),
    sa.Column('ref_num_type', sa.String(), nullable=False),
    sa.Column('case_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_number'], ['odycvcit.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_odycvcit_reference_numbers_case_number', 'odycvcit_reference_numbers', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('odycvcit_restitutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restitution_amount', sa.Numeric(), nullable=True),
    sa.Column('restitution_entered_date', sa.Date(), nullable=True),
    sa.Column('restitution_entered_date_str', sa.String(), nullable=True),
    sa.Column('other_cost_amount', sa.Numeric(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_number'], ['odycvcit.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_odycvcit_restitutions_case_number', 'odycvcit_restitutions', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('odycvcit_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_type', sa.String(), nullable=False),
    sa.Column('issued_date', sa.Date(), nullable=True),
    sa.Column('issued_date_str', sa.String(), nullable=True),
    sa.Column('service_status', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_number'], ['odycvcit.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_odycvcit_services_case_number', 'odycvcit_services', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('odycvcit_sex_offender_registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_number'], ['odycvcit.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_odycvcit_sex_offender_registrations_case_number', 'odycvcit_sex_offender_registrations', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('odycvcit_warrants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warrant_type', sa.String(), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('issue_date_str', sa.String(), nullable=True),
    sa.Column('last_status', sa.String(), nullable=True),
    sa.Column('status_date', sa.Date(), nullable=True),
    sa.Column('status_date_str', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_number'], ['odycvcit.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_odycvcit_warrants_case_number', 'odycvcit_warrants', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('odycvcit_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(), nullable=False),
    sa.Column('alias_type', sa.String(), nullable=False),
    sa.Column('defendant_id', sa.Integer(), nullable=True),
    sa.Column('party_id', sa.Integer(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_number'], ['odycvcit.case_number'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['defendant_id'], ['odycvcit_defendants.id'], ),
    sa.ForeignKeyConstraint(['party_id'], ['odycvcit_involved_parties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_odycvcit_aliases_case_number', 'odycvcit_aliases', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('odycvcit_attorneys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('appearance_date', sa.Date(), nullable=True),
    sa.Column('appearance_date_str', sa.String(), nullable=True),
    sa.Column('removal_date', sa.Date(), nullable=True),
    sa.Column('removal_date_str', sa.String(), nullable=True),
    sa.Column('address_1', sa.String(), nullable=True),
    sa.Column('address_2', sa.String(), nullable=True),
    sa.Column('address_3', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('defendant_id', sa.Integer(), nullable=True),
    sa.Column('party_id', sa.Integer(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_number'], ['odycvcit.case_number'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['defendant_id'], ['odycvcit_defendants.id'], ),
    sa.ForeignKeyConstraint(['party_id'], ['odycvcit_involved_parties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_odycvcit_attorneys_case_number', 'odycvcit_attorneys', ['case_number'], unique=False, postgresql_using='hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ixh_odycvcit_attorneys_case_number', table_name='odycvcit_attorneys')
    op.drop_table('odycvcit_attorneys')
    op.drop_index('ixh_odycvcit_aliases_case_number', table_name='odycvcit_aliases')
    op.drop_table('odycvcit_aliases')
    op.drop_index('ixh_odycvcit_warrants_case_number', table_name='odycvcit_warrants')
    op.drop_table('odycvcit_warrants')
    op.drop_index('ixh_odycvcit_sex_offender_registrations_case_number', table_name='odycvcit_sex_offender_registrations')
    op.drop_table('odycvcit_sex_offender_registrations')
    op.drop_index('ixh_odycvcit_services_case_number', table_name='odycvcit_services')
    op.drop_table('odycvcit_services')
    op.drop_index('ixh_odycvcit_restitutions_case_number', table_name='odycvcit_restitutions')
    op.drop_table('odycvcit_restitutions')
    op.drop_index('ixh_odycvcit_reference_numbers_case_number', table_name='odycvcit_reference_numbers')
    op.drop_table('odycvcit_reference_numbers')
    op.drop_index('ixh_odycvcit_probation_case_number', table_name='odycvcit_probation')
    op.drop_table('odycvcit_probation')
    op.drop_index('ixh_odycvcit_involved_parties_case_number', table_name='odycvcit_involved_parties')
    op.drop_table('odycvcit_involved_parties')
    op.drop_index('ixh_odycvcit_defendants_case_number', table_name='odycvcit_defendants')
    op.drop_table('odycvcit_defendants')
    op.drop_index('ixh_odycvcit_court_schedule_case_number', table_name='odycvcit_court_schedule')
    op.drop_table('odycvcit_court_schedule')
    op.drop_index('ixh_odycvcit_bond_settings_case_number', table_name='odycvcit_bond_settings')
    op.drop_table('odycvcit_bond_settings')
    op.drop_index('ixh_odycvcit_bail_bonds_case_number', table_name='odycvcit_bail_bonds')
    op.drop_table('odycvcit_bail_bonds')
    op.drop_index('ixh_ODYCVCIT_documents_case_number', table_name='ODYCVCIT_documents')
    op.drop_table('ODYCVCIT_documents')
    op.drop_index('ixh_odycvcit_case_number', table_name='odycvcit')
    op.drop_table('odycvcit')
    op.drop_index('ixh_odycvcit_charges_case_number', table_name='odycvcit_charges')
    op.drop_table('odycvcit_charges')
    # ### end Alembic commands ###
