"""Add allowed_values array to column_metadata

Revision ID: baa609bd1160
Revises: b8eb352e4f9e
Create Date: 2021-08-09 01:37:13.925354

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'baa609bd1160'
down_revision = 'b8eb352e4f9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('column_metadata', sa.Column('allowed_values', postgresql.ARRAY(sa.String(), dimensions=1), nullable=True))
    # ### end Alembic commands ###  


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('column_metadata', 'allowed_values')
    # ### end Alembic commands ###
