"""Add missing fields in MCCR

Revision ID: bb071f4f29f2
Revises: 5be140385f46
Create Date: 2021-10-12 10:05:20.555959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb071f4f29f2'
down_revision = '5be140385f46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mccr_dockets', sa.Column('status', sa.String(), nullable=True))
    op.add_column('mccr_dockets', sa.Column('ruling_judge', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mccr_dockets', 'ruling_judge')
    op.drop_column('mccr_dockets', 'status')
    # ### end Alembic commands ###
