"""split party address table from CC parties

Revision ID: bc9d0d8db2e2
Revises: a87c38b98bac
Create Date: 2018-05-20 20:21:37.017875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc9d0d8db2e2'
down_revision = 'a87c38b98bac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cc_party_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plaintiff_id', sa.Integer(), nullable=True),
    sa.Column('defendant_id', sa.Integer(), nullable=True),
    sa.Column('related_person_id', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_number'], ['cc.case_number'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['defendant_id'], ['cc_defendants.id'], ),
    sa.ForeignKeyConstraint(['plaintiff_id'], ['cc_plaintiffs.id'], ),
    sa.ForeignKeyConstraint(['related_person_id'], ['cc_related_persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('cc_defendants', 'address')
    op.drop_column('cc_defendants', 'state')
    op.drop_column('cc_defendants', 'city')
    op.drop_column('cc_defendants', 'zip_code')
    op.drop_column('cc_plaintiffs', 'address')
    op.drop_column('cc_plaintiffs', 'state')
    op.drop_column('cc_plaintiffs', 'city')
    op.drop_column('cc_plaintiffs', 'zip_code')
    op.drop_column('cc_related_persons', 'address')
    op.drop_column('cc_related_persons', 'state')
    op.drop_column('cc_related_persons', 'city')
    op.drop_column('cc_related_persons', 'zip_code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cc_related_persons', sa.Column('zip_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('cc_related_persons', sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('cc_related_persons', sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('cc_related_persons', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('cc_plaintiffs', sa.Column('zip_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('cc_plaintiffs', sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('cc_plaintiffs', sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('cc_plaintiffs', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('cc_defendants', sa.Column('zip_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('cc_defendants', sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('cc_defendants', sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('cc_defendants', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('cc_party_addresses')
    # ### end Alembic commands ###
