"""Added DOB to odycivil_involved_parties

Revision ID: bea2e05bd9fe
Revises: f5a2f305394e
Create Date: 2021-07-02 14:34:49.531911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bea2e05bd9fe'
down_revision = 'fa053738a6c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('odycivil_involved_parties', sa.Column('DOB', sa.Date(), nullable=True))
    op.add_column('odycivil_involved_parties', sa.Column('DOB_str', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('odycivil_involved_parties', 'DOB_str')
    op.drop_column('odycivil_involved_parties', 'DOB')
    # ### end Alembic commands ###
