"""Additional columns for ODYCIVILJudgmentComment

Revision ID: c2f35a46de03
Revises: 03d0db20af8d
Create Date: 2021-03-01 09:41:26.339935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2f35a46de03'
down_revision = '03d0db20af8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('odycivil_judgment_comments', sa.Column('amendcorrect', sa.String(), nullable=True))
    op.add_column('odycivil_judgment_comments', sa.Column('cc_recorded_date', sa.Date(), nullable=True))
    op.add_column('odycivil_judgment_comments', sa.Column('cc_recorded_date_str', sa.String(), nullable=True))
    op.add_column('odycivil_judgment_comments', sa.Column('defreason', sa.String(), nullable=True))
    op.add_column('odycivil_judgment_comments', sa.Column('freetext', sa.String(), nullable=True))
    op.add_column('odycivil_judgment_comments', sa.Column('post_interest_rate', sa.String(), nullable=True))
    op.add_column('odycivil_judgment_comments', sa.Column('printdate', sa.Date(), nullable=True))
    op.add_column('odycivil_judgment_comments', sa.Column('printdate_str', sa.String(), nullable=True))
    op.add_column('odycivil_judgment_comments', sa.Column('satisfaction_date', sa.Date(), nullable=True))
    op.add_column('odycivil_judgment_comments', sa.Column('satisfaction_date_str', sa.String(), nullable=True))
    op.add_column('odycivil_judgment_comments', sa.Column('sat_date_entered', sa.Date(), nullable=True))
    op.add_column('odycivil_judgment_comments', sa.Column('sat_date_entered_str', sa.String(), nullable=True))
    op.add_column('odycivil_judgment_comments', sa.Column('totdecimalprin', sa.Numeric(), nullable=True))
    op.add_column('odycivil_judgment_comments', sa.Column('totalinterest', sa.Numeric(), nullable=True))
    op.add_column('odycivil_judgment_comments', sa.Column('totaljudg', sa.Numeric(), nullable=True))
    op.add_column('odycivil_judgment_comments', sa.Column('totalprincipal', sa.Numeric(), nullable=True))
    op.alter_column('odycivil_judgment_comments', 'damanges_pop', new_column_name='damages_pop')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('odycivil_judgment_comments', 'damages_pop', new_column_name='damanges_pop')
    op.drop_column('odycivil_judgment_comments', 'totalprincipal')
    op.drop_column('odycivil_judgment_comments', 'totaljudg')
    op.drop_column('odycivil_judgment_comments', 'totalinterest')
    op.drop_column('odycivil_judgment_comments', 'totdecimalprin')
    op.drop_column('odycivil_judgment_comments', 'sat_date_entered_str')
    op.drop_column('odycivil_judgment_comments', 'sat_date_entered')
    op.drop_column('odycivil_judgment_comments', 'satisfaction_date_str')
    op.drop_column('odycivil_judgment_comments', 'satisfaction_date')
    op.drop_column('odycivil_judgment_comments', 'printdate_str')
    op.drop_column('odycivil_judgment_comments', 'printdate')
    op.drop_column('odycivil_judgment_comments', 'post_interest_rate')
    op.drop_column('odycivil_judgment_comments', 'freetext')
    op.drop_column('odycivil_judgment_comments', 'defreason')
    op.drop_column('odycivil_judgment_comments', 'cc_recorded_date_str')
    op.drop_column('odycivil_judgment_comments', 'cc_recorded_date')
    op.drop_column('odycivil_judgment_comments', 'amendcorrect')
    # ### end Alembic commands ###
