"""add mortgage to bail_and_bond

Revision ID: c3420fc7aeaf
Revises: 63f37461c971
Create Date: 2018-05-05 20:34:29.490423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3420fc7aeaf'
down_revision = '63f37461c971'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('DSCR_case_number_fkey', 'DSCR', type_='foreignkey')
    op.create_foreign_key(None, 'DSCR', 'cases', ['case_number'], ['case_number'], ondelete='CASCADE')
    op.add_column('bail_and_bond', sa.Column('mortgage', sa.Numeric(), nullable=True))
    op.drop_constraint('case_events_case_number_fkey', 'case_events', type_='foreignkey')
    op.create_foreign_key(None, 'case_events', 'cases', ['case_number'], ['case_number'], ondelete='CASCADE')
    op.drop_constraint('defendant_alias_case_number_fkey', 'defendant_alias', type_='foreignkey')
    op.create_foreign_key(None, 'defendant_alias', 'cases', ['case_number'], ['case_number'], ondelete='CASCADE')
    op.drop_constraint('defendants_case_number_fkey', 'defendants', type_='foreignkey')
    op.create_foreign_key(None, 'defendants', 'cases', ['case_number'], ['case_number'], ondelete='CASCADE')
    op.drop_constraint('charges_case_number_fkey', 'dscr_charges', type_='foreignkey')
    op.create_foreign_key(None, 'dscr_charges', 'cases', ['case_number'], ['case_number'], ondelete='CASCADE')
    op.drop_constraint('court_schedule_case_number_fkey', 'dscr_court_schedule', type_='foreignkey')
    op.create_foreign_key(None, 'dscr_court_schedule', 'cases', ['case_number'], ['case_number'], ondelete='CASCADE')
    op.drop_constraint('related_persons_case_number_fkey', 'related_persons', type_='foreignkey')
    op.create_foreign_key(None, 'related_persons', 'cases', ['case_number'], ['case_number'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'related_persons', type_='foreignkey')
    op.create_foreign_key('related_persons_case_number_fkey', 'related_persons', 'cases', ['case_number'], ['case_number'])
    op.drop_constraint(None, 'dscr_court_schedule', type_='foreignkey')
    op.create_foreign_key('court_schedule_case_number_fkey', 'dscr_court_schedule', 'cases', ['case_number'], ['case_number'])
    op.drop_constraint(None, 'dscr_charges', type_='foreignkey')
    op.create_foreign_key('charges_case_number_fkey', 'dscr_charges', 'cases', ['case_number'], ['case_number'])
    op.drop_constraint(None, 'defendants', type_='foreignkey')
    op.create_foreign_key('defendants_case_number_fkey', 'defendants', 'cases', ['case_number'], ['case_number'])
    op.drop_constraint(None, 'defendant_alias', type_='foreignkey')
    op.create_foreign_key('defendant_alias_case_number_fkey', 'defendant_alias', 'cases', ['case_number'], ['case_number'])
    op.drop_constraint(None, 'case_events', type_='foreignkey')
    op.create_foreign_key('case_events_case_number_fkey', 'case_events', 'cases', ['case_number'], ['case_number'])
    op.drop_column('bail_and_bond', 'mortgage')
    op.drop_constraint(None, 'DSCR', type_='foreignkey')
    op.create_foreign_key('DSCR_case_number_fkey', 'DSCR', 'cases', ['case_number'], ['case_number'])
    # ### end Alembic commands ###
