"""Add ODYCIVIL

Revision ID: c53bda737bbe
Revises: b016102d2c6a
Create Date: 2021-02-28 19:47:03.901571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c53bda737bbe'
down_revision = 'b016102d2c6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('odycivil',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('court_system', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('case_title', sa.String(), nullable=True),
    sa.Column('case_type', sa.String(), nullable=True),
    sa.Column('filing_date', sa.Date(), nullable=True),
    sa.Column('filing_date_str', sa.String(), nullable=True),
    sa.Column('case_status', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_number'], ['cases.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_number')
    )
    op.create_index('ixh_odycivil_case_number', 'odycivil', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('odycivil_bail_bonds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bond_type', sa.String(), nullable=True),
    sa.Column('bond_amount_set', sa.Numeric(), nullable=True),
    sa.Column('bond_status_date', sa.Date(), nullable=True),
    sa.Column('bond_status_date_str', sa.String(), nullable=True),
    sa.Column('bond_status', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_number'], ['odycivil.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_odycivil_bail_bonds_case_number', 'odycivil_bail_bonds', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('odycivil_bond_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bail_date', sa.Date(), nullable=True),
    sa.Column('bail_date_str', sa.String(), nullable=True),
    sa.Column('bail_setting_type', sa.String(), nullable=True),
    sa.Column('bail_amount', sa.Numeric(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_number'], ['odycivil.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_odycivil_bond_settings_case_number', 'odycivil_bond_settings', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('odycivil_causes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_date', sa.Date(), nullable=True),
    sa.Column('file_date_str', sa.String(), nullable=True),
    sa.Column('cause_description', sa.String(), nullable=True),
    sa.Column('filed_by', sa.String(), nullable=True),
    sa.Column('filed_against', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_number'], ['odycivil.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_odycivil_causes_case_number', 'odycivil_causes', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('odycivil_court_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('date_str', sa.String(), nullable=True),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('time_str', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('room', sa.String(), nullable=True),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_number'], ['odycivil.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_odycivil_court_schedule_case_number', 'odycivil_court_schedule', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('odycivil_defendants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('race', sa.String(), nullable=True),
    sa.Column('sex', sa.String(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('DOB', sa.Date(), nullable=True),
    sa.Column('DOB_str', sa.String(), nullable=True),
    sa.Column('address_1', sa.String(), nullable=True),
    sa.Column('address_2', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_number'], ['odycivil.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_odycivil_defendants_case_number', 'odycivil_defendants', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('odycivil_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_date', sa.Date(), nullable=True),
    sa.Column('file_date_str', sa.String(), nullable=True),
    sa.Column('filed_by', sa.String(), nullable=True),
    sa.Column('document_name', sa.String(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_number'], ['odycivil.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_odycivil_documents_case_number', 'odycivil_documents', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('odycivil_involved_parties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('party_type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address_1', sa.String(), nullable=True),
    sa.Column('address_2', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_number'], ['odycivil.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_odycivil_involved_parties_case_number', 'odycivil_involved_parties', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('odycivil_judgment_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(), nullable=True),
    sa.Column('interest', sa.Numeric(), nullable=True),
    sa.Column('atty_fee', sa.Numeric(), nullable=True),
    sa.Column('judg_cost', sa.Numeric(), nullable=True),
    sa.Column('other_amount', sa.Numeric(), nullable=True),
    sa.Column('poss_of_prop', sa.Numeric(), nullable=True),
    sa.Column('damanges_pop', sa.Numeric(), nullable=True),
    sa.Column('value_of_prop', sa.Numeric(), nullable=True),
    sa.Column('damgs_val_of_prop', sa.Numeric(), nullable=True),
    sa.Column('repl_detn_amnt', sa.Numeric(), nullable=True),
    sa.Column('judg_type', sa.String(), nullable=True),
    sa.Column('judg_district', sa.String(), nullable=True),
    sa.Column('judg_location', sa.String(), nullable=True),
    sa.Column('judg_date', sa.Date(), nullable=True),
    sa.Column('judg_date_str', sa.String(), nullable=True),
    sa.Column('date_entered', sa.Date(), nullable=True),
    sa.Column('date_entered_str', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_number'], ['odycivil.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_odycivil_judgment_comments_case_number', 'odycivil_judgment_comments', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('odycivil_judgments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('judgment_type', sa.String(), nullable=True),
    sa.Column('judgment_description', sa.String(), nullable=True),
    sa.Column('judgment_event_type', sa.String(), nullable=True),
    sa.Column('judgment_against', sa.String(), nullable=True),
    sa.Column('judgment_in_favor_of', sa.String(), nullable=True),
    sa.Column('judgment_ordered_date', sa.Date(), nullable=True),
    sa.Column('judgment_ordered_date_str', sa.String(), nullable=True),
    sa.Column('judgment_entry_date', sa.Date(), nullable=True),
    sa.Column('judgment_entry_date_str', sa.String(), nullable=True),
    sa.Column('postjudgment_interest', sa.String(), nullable=True),
    sa.Column('principal_amount', sa.Numeric(), nullable=True),
    sa.Column('prejudgment_interest', sa.Numeric(), nullable=True),
    sa.Column('other_fee', sa.Numeric(), nullable=True),
    sa.Column('service_fee', sa.Numeric(), nullable=True),
    sa.Column('appearance_fee', sa.Numeric(), nullable=True),
    sa.Column('witness_fee', sa.Numeric(), nullable=True),
    sa.Column('filing_fee', sa.Numeric(), nullable=True),
    sa.Column('attorney_fee', sa.Numeric(), nullable=True),
    sa.Column('amount_of_judgment', sa.Numeric(), nullable=True),
    sa.Column('total_indexed_judgment', sa.Numeric(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('awarded_to', sa.String(), nullable=True),
    sa.Column('property_value', sa.Numeric(), nullable=True),
    sa.Column('damages', sa.Numeric(), nullable=True),
    sa.Column('property_description', sa.String(), nullable=True),
    sa.Column('replivin_or_detinue', sa.String(), nullable=True),
    sa.Column('r_d_amount', sa.Numeric(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_number'], ['odycivil.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_odycivil_judgment_case_number', 'odycivil_judgments', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('odycivil_reference_numbers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ref_num', sa.String(), nullable=False),
    sa.Column('ref_num_type', sa.String(), nullable=False),
    sa.Column('case_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_number'], ['odycivil.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_odycivil_reference_numbers_case_number', 'odycivil_reference_numbers', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('odycivil_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_type', sa.String(), nullable=False),
    sa.Column('issued_date', sa.Date(), nullable=True),
    sa.Column('issued_date_str', sa.String(), nullable=True),
    sa.Column('service_status', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_number'], ['odycivil.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_odycivil_services_case_number', 'odycivil_services', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('odycivil_warrants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warrant_type', sa.String(), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('issue_date_str', sa.String(), nullable=True),
    sa.Column('last_status', sa.String(), nullable=True),
    sa.Column('status_date', sa.Date(), nullable=True),
    sa.Column('status_date_str', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_number'], ['odycivil.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_odycivil_warrants_case_number', 'odycivil_warrants', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('odycivil_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(), nullable=False),
    sa.Column('alias_type', sa.String(), nullable=False),
    sa.Column('defendant_id', sa.Integer(), nullable=True),
    sa.Column('party_id', sa.Integer(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_number'], ['odycivil.case_number'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['defendant_id'], ['odycivil_defendants.id'], ),
    sa.ForeignKeyConstraint(['party_id'], ['odycivil_involved_parties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_odycivil_aliases_case_number', 'odycivil_aliases', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('odycivil_attorneys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('appearance_date', sa.Date(), nullable=True),
    sa.Column('appearance_date_str', sa.String(), nullable=True),
    sa.Column('removal_date', sa.Date(), nullable=True),
    sa.Column('removal_date_str', sa.String(), nullable=True),
    sa.Column('address_1', sa.String(), nullable=True),
    sa.Column('address_2', sa.String(), nullable=True),
    sa.Column('address_3', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('defendant_id', sa.Integer(), nullable=True),
    sa.Column('party_id', sa.Integer(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_number'], ['odycivil.case_number'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['defendant_id'], ['odycivil_defendants.id'], ),
    sa.ForeignKeyConstraint(['party_id'], ['odycivil_involved_parties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_odycivil_attorneys_case_number', 'odycivil_attorneys', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('odycivil_cause_remedies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('remedy_type', sa.String(), nullable=True),
    sa.Column('amount', sa.Numeric(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('cause_id', sa.Integer(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_number'], ['odycivil.case_number'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cause_id'], ['odycivil_causes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_odycivil_cause_remedies_case_number', 'odycivil_cause_remedies', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('odycivil_judgment_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('judgment_status', sa.String(), nullable=False),
    sa.Column('judgment_date', sa.Date(), nullable=True),
    sa.Column('judgment_date_str', sa.String(), nullable=True),
    sa.Column('judgment_id', sa.Integer(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_number'], ['odycivil.case_number'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['judgment_id'], ['odycivil_judgments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_odycivil_judgment_status_case_number', 'odycivil_judgment_statuses', ['case_number'], unique=False, postgresql_using='hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ixh_odycivil_judgment_status_case_number', table_name='odycivil_judgment_statuses')
    op.drop_table('odycivil_judgment_statuses')
    op.drop_index('ixh_odycivil_cause_remedies_case_number', table_name='odycivil_cause_remedies')
    op.drop_table('odycivil_cause_remedies')
    op.drop_index('ixh_odycivil_attorneys_case_number', table_name='odycivil_attorneys')
    op.drop_table('odycivil_attorneys')
    op.drop_index('ixh_odycivil_aliases_case_number', table_name='odycivil_aliases')
    op.drop_table('odycivil_aliases')
    op.drop_index('ixh_odycivil_warrants_case_number', table_name='odycivil_warrants')
    op.drop_table('odycivil_warrants')
    op.drop_index('ixh_odycivil_services_case_number', table_name='odycivil_services')
    op.drop_table('odycivil_services')
    op.drop_index('ixh_odycivil_reference_numbers_case_number', table_name='odycivil_reference_numbers')
    op.drop_table('odycivil_reference_numbers')
    op.drop_index('ixh_odycivil_judgment_case_number', table_name='odycivil_judgments')
    op.drop_table('odycivil_judgments')
    op.drop_index('ixh_odycivil_judgment_comments_case_number', table_name='odycivil_judgment_comments')
    op.drop_table('odycivil_judgment_comments')
    op.drop_index('ixh_odycivil_involved_parties_case_number', table_name='odycivil_involved_parties')
    op.drop_table('odycivil_involved_parties')
    op.drop_index('ixh_odycivil_documents_case_number', table_name='odycivil_documents')
    op.drop_table('odycivil_documents')
    op.drop_index('ixh_odycivil_defendants_case_number', table_name='odycivil_defendants')
    op.drop_table('odycivil_defendants')
    op.drop_index('ixh_odycivil_court_schedule_case_number', table_name='odycivil_court_schedule')
    op.drop_table('odycivil_court_schedule')
    op.drop_index('ixh_odycivil_causes_case_number', table_name='odycivil_causes')
    op.drop_table('odycivil_causes')
    op.drop_index('ixh_odycivil_bond_settings_case_number', table_name='odycivil_bond_settings')
    op.drop_table('odycivil_bond_settings')
    op.drop_index('ixh_odycivil_bail_bonds_case_number', table_name='odycivil_bail_bonds')
    op.drop_table('odycivil_bail_bonds')
    op.drop_index('ixh_odycivil_case_number', table_name='odycivil')
    op.drop_table('odycivil')
    # ### end Alembic commands ###
