"""change another dscr data type

Revision ID: c6965a9b34fe
Revises: e3ca8834d437
Create Date: 2018-05-23 16:56:39.189270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6965a9b34fe'
down_revision = 'e3ca8834d437'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dscr_charges','credit_time_served',type_=sa.String)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dscr_charges','credit_time_served',type_=sa.Integer)
    # ### end Alembic commands ###
