"""convert DSK8 tracking number to string

Revision ID: c72ff2a44e3d
Revises: 3df211a638f7
Create Date: 2018-11-26 17:02:49.408284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c72ff2a44e3d'
down_revision = '3df211a638f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dsk8','tracking_number',type_=sa.String)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dsk8','tracking_number',type_=sa.BigInteger)
    # ### end Alembic commands ###
