"""Remove checked_expunged_charges from cases. nullable=False for case_number fields.

Revision ID: cbaf431ce937
Revises: e81039c4f948
Create Date: 2021-08-02 02:28:05.032486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbaf431ce937'
down_revision = 'e81039c4f948'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'checked_expunged_charges')
    op.alter_column('ODYCVCIT_documents', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('cc_attorneys', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('cc_court_schedule', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('cc_defendants', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('cc_district_case_numbers', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('cc_documents', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('cc_judgment_modifications', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('cc_judgments', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('cc_judgments_against', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('cc_judgments_in_favor', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('cc_party_addresses', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('cc_party_alias', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('cc_plaintiffs', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('cc_related_persons', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('cc_support_orders', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('dscivil_complaints', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('dscivil_events', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('dscivil_hearings', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('dscivil_judgments', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('dscivil_related_persons', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('dscivil_trials', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('dscr_bail_events', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('dscr_defendant_aliases', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('dscr_defendants', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('dscr_events', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('dscr_related_persons', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('dscr_trials', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('dsk8_bail_and_bond', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('dsk8_bondsman', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('dsk8_defendant_aliases', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('dsk8_defendants', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('dsk8_events', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('dsk8_related_persons', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('dsk8_trials', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('dstraf_charges', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('dstraf_defendants', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('dstraf_dispositions', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('dstraf_events', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('dstraf_related_persons', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('dstraf_trials', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('odycivil_aliases', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('odycivil_attorneys', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('odycivil_bail_bonds', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('odycivil_bond_settings', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('odycivil_cause_remedies', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('odycivil_causes', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('odycivil_court_schedule', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('odycivil_defendants', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('odycivil_dispositions', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('odycivil_documents', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('odycivil_involved_parties', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('odycivil_judgment_comments', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('odycivil_judgment_statuses', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('odycivil_judgments', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('odycivil_reference_numbers', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('odycivil_services', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('odycivil_warrants', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('odycrim_aliases', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('odycrim_attorneys', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('odycrim_bail_bonds', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('odycrim_bond_settings', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('odycrim_court_schedule', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('odycrim_defendants', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('odycrim_documents', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('odycrim_involved_parties', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('odycrim_probation', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('odycrim_reference_numbers', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('odycrim_restitutions', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('odycrim_services', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('odycrim_sex_offender_registrations', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('odycrim_warrants', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('odycvcit_aliases', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('odycvcit_attorneys', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('odycvcit_bail_bonds', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('odycvcit_bond_settings', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('odycvcit_court_schedule', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('odycvcit_defendants', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('odycvcit_involved_parties', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('odycvcit_probation', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('odycvcit_reference_numbers', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('odycvcit_restitutions', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('odycvcit_services', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('odycvcit_sex_offender_registrations', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('odycvcit_warrants', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('odytraf_aliases', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('odytraf_attorneys', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('odytraf_bail_bonds', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('odytraf_bond_settings', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('odytraf_court_schedule', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('odytraf_defendants', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('odytraf_documents', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('odytraf_involved_parties', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('odytraf_reference_numbers', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('odytraf_services', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('odytraf_warrants', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('odytraf_warrants', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('odytraf_services', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('odytraf_reference_numbers', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('odytraf_involved_parties', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('odytraf_documents', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('odytraf_defendants', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('odytraf_court_schedule', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('odytraf_bond_settings', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('odytraf_bail_bonds', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('odytraf_attorneys', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('odytraf_aliases', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('odycvcit_warrants', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('odycvcit_sex_offender_registrations', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('odycvcit_services', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('odycvcit_restitutions', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('odycvcit_reference_numbers', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('odycvcit_probation', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('odycvcit_involved_parties', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('odycvcit_defendants', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('odycvcit_court_schedule', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('odycvcit_bond_settings', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('odycvcit_bail_bonds', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('odycvcit_attorneys', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('odycvcit_aliases', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('odycrim_warrants', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('odycrim_sex_offender_registrations', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('odycrim_services', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('odycrim_restitutions', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('odycrim_reference_numbers', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('odycrim_probation', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('odycrim_involved_parties', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('odycrim_documents', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('odycrim_defendants', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('odycrim_court_schedule', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('odycrim_bond_settings', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('odycrim_bail_bonds', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('odycrim_attorneys', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('odycrim_aliases', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('odycivil_warrants', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('odycivil_services', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('odycivil_reference_numbers', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('odycivil_judgments', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('odycivil_judgment_statuses', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('odycivil_judgment_comments', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('odycivil_involved_parties', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('odycivil_documents', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('odycivil_dispositions', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('odycivil_defendants', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('odycivil_court_schedule', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('odycivil_causes', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('odycivil_cause_remedies', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('odycivil_bond_settings', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('odycivil_bail_bonds', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('odycivil_attorneys', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('odycivil_aliases', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('dstraf_trials', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('dstraf_related_persons', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('dstraf_events', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('dstraf_dispositions', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('dstraf_defendants', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('dstraf_charges', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('dsk8_trials', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('dsk8_related_persons', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('dsk8_events', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('dsk8_defendants', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('dsk8_defendant_aliases', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('dsk8_bondsman', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('dsk8_bail_and_bond', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('dscr_trials', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('dscr_related_persons', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('dscr_events', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('dscr_defendants', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('dscr_defendant_aliases', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('dscr_bail_events', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('dscivil_trials', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('dscivil_related_persons', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('dscivil_judgments', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('dscivil_hearings', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('dscivil_events', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('dscivil_complaints', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('cc_support_orders', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('cc_related_persons', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('cc_plaintiffs', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('cc_party_alias', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('cc_party_addresses', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('cc_judgments_in_favor', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('cc_judgments_against', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('cc_judgments', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('cc_judgment_modifications', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('cc_documents', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('cc_district_case_numbers', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('cc_defendants', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('cc_court_schedule', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('cc_attorneys', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('ODYCVCIT_documents', 'case_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('cases', sa.Column('checked_expunged_charges', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
