"""Add K models

Revision ID: d5cb6fe00424
Revises: e8ac4686db0c
Create Date: 2021-08-23 04:36:33.419147

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd5cb6fe00424'
down_revision = 'e8ac4686db0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('k',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('court_system', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('case_type', sa.String(), nullable=True),
    sa.Column('filing_date', sa.Date(), nullable=True),
    sa.Column('filing_date_str', sa.String(), nullable=True),
    sa.Column('case_status', sa.String(), nullable=True),
    sa.Column('case_disposition', sa.String(), nullable=True),
    sa.Column('disposition_date', sa.Date(), nullable=True),
    sa.Column('disposition_date_str', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_number'], ['cases.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_number')
    )
    op.create_index('ixh_k_case_number', 'k', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('k_charges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('charge_number', sa.Integer(), nullable=True),
    sa.Column('expunged', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('cjis_code', sa.String(), nullable=True),
    sa.Column('statute_code', sa.String(), nullable=True),
    sa.Column('charge_description', sa.String(), nullable=True),
    sa.Column('charge_class', sa.String(), nullable=True),
    sa.Column('probable_cause', sa.Boolean(), nullable=True),
    sa.Column('offense_date_from', sa.Date(), nullable=True),
    sa.Column('offense_date_from_str', sa.String(), nullable=True),
    sa.Column('offense_date_to', sa.Date(), nullable=True),
    sa.Column('offense_date_to_str', sa.String(), nullable=True),
    sa.Column('arrest_tracking_number', sa.String(), nullable=True),
    sa.Column('citation', sa.String(), nullable=True),
    sa.Column('charge_amend_number', sa.Integer(), nullable=True),
    sa.Column('sentence_version', sa.Integer(), nullable=True),
    sa.Column('agency_name', sa.String(), nullable=True),
    sa.Column('officer_id', sa.String(), nullable=True),
    sa.Column('plea', sa.String(), nullable=True),
    sa.Column('plea_date', sa.Date(), nullable=True),
    sa.Column('plea_date_str', sa.String(), nullable=True),
    sa.Column('disposition', sa.String(), nullable=True),
    sa.Column('disposition_date', sa.Date(), nullable=True),
    sa.Column('disposition_date_str', sa.String(), nullable=True),
    sa.Column('converted_disposition', sa.String(), nullable=True),
    sa.Column('jail_life', sa.Boolean(), nullable=True),
    sa.Column('jail_death', sa.Boolean(), nullable=True),
    sa.Column('jail_start_date', sa.Date(), nullable=True),
    sa.Column('jail_start_date_str', sa.String(), nullable=True),
    sa.Column('jail_cons_conc', sa.String(), nullable=True),
    sa.Column('jail_years', sa.Integer(), nullable=True),
    sa.Column('jail_months', sa.Integer(), nullable=True),
    sa.Column('jail_days', sa.Integer(), nullable=True),
    sa.Column('jail_hours', sa.Integer(), nullable=True),
    sa.Column('jail_suspended_term', sa.String(), nullable=True),
    sa.Column('jail_suspended_years', sa.Integer(), nullable=True),
    sa.Column('jail_suspended_months', sa.Integer(), nullable=True),
    sa.Column('jail_suspended_days', sa.Integer(), nullable=True),
    sa.Column('jail_suspended_hours', sa.Integer(), nullable=True),
    sa.Column('jail_suspend_all_but_years', sa.Integer(), nullable=True),
    sa.Column('jail_suspend_all_but_months', sa.Integer(), nullable=True),
    sa.Column('jail_suspend_all_but_days', sa.Integer(), nullable=True),
    sa.Column('jail_suspend_all_but_hours', sa.Integer(), nullable=True),
    sa.Column('probation_years', sa.Integer(), nullable=True),
    sa.Column('probation_months', sa.Integer(), nullable=True),
    sa.Column('probation_days', sa.Integer(), nullable=True),
    sa.Column('probation_hours', sa.Integer(), nullable=True),
    sa.Column('probation_supervised_years', sa.Integer(), nullable=True),
    sa.Column('probation_supervised_months', sa.Integer(), nullable=True),
    sa.Column('probation_supervised_days', sa.Integer(), nullable=True),
    sa.Column('probation_supervised_hours', sa.Integer(), nullable=True),
    sa.Column('probation_unsupervised_years', sa.Integer(), nullable=True),
    sa.Column('probation_unsupervised_months', sa.Integer(), nullable=True),
    sa.Column('probation_unsupervised_days', sa.Integer(), nullable=True),
    sa.Column('probation_unsupervised_hours', sa.Integer(), nullable=True),
    sa.Column('probation_text', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_number'], ['k.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_k_charges_case_number', 'k_charges', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('k_court_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('notice_date', sa.Date(), nullable=True),
    sa.Column('notice_date_str', sa.String(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('event_date_str', sa.String(), nullable=True),
    sa.Column('event_time', sa.Time(), nullable=True),
    sa.Column('event_time_str', sa.String(), nullable=True),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('result_date', sa.Date(), nullable=True),
    sa.Column('result_date_str', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_number'], ['k.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_k_court_schedule_case_number', 'k_court_schedule', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('k_defendants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('party_type', sa.String(), nullable=True),
    sa.Column('party_number', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('business_org_name', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_number'], ['k.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_k_defendants_case_number', 'k_defendants', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('k_district_case_numbers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('district_case_number', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_number'], ['k.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_k_district_case_numbers_case_number', 'k_district_case_numbers', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('k_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_number', sa.Integer(), nullable=True),
    sa.Column('sequence_number', sa.Integer(), nullable=True),
    sa.Column('file_date', sa.Date(), nullable=True),
    sa.Column('file_date_str', sa.String(), nullable=True),
    sa.Column('entered_date', sa.Date(), nullable=True),
    sa.Column('entered_date_str', sa.String(), nullable=True),
    sa.Column('decision', sa.String(), nullable=True),
    sa.Column('party_type', sa.String(), nullable=True),
    sa.Column('party_number', sa.Integer(), nullable=True),
    sa.Column('document_name', sa.String(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_number'], ['k.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_k_documents_case_number', 'k_documents', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('k_judgments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('judgment_type', sa.String(), nullable=True),
    sa.Column('entered_date', sa.Date(), nullable=True),
    sa.Column('entered_date_str', sa.String(), nullable=True),
    sa.Column('amount', sa.Numeric(), nullable=True),
    sa.Column('amount_other', sa.String(), nullable=True),
    sa.Column('prejudgment_interest', sa.Numeric(), nullable=True),
    sa.Column('appearance_fee', sa.Numeric(), nullable=True),
    sa.Column('filing_fee', sa.Numeric(), nullable=True),
    sa.Column('other_fee', sa.Numeric(), nullable=True),
    sa.Column('service_fee', sa.Numeric(), nullable=True),
    sa.Column('witness_fee', sa.Numeric(), nullable=True),
    sa.Column('attorney_fee', sa.Numeric(), nullable=True),
    sa.Column('total_indexed_judgment', sa.Numeric(), nullable=True),
    sa.Column('tij_other', sa.String(), nullable=True),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_number'], ['k.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_k_judgments_case_number', 'k_judgments', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('k_plaintiffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('party_type', sa.String(), nullable=True),
    sa.Column('party_number', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('business_org_name', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_number'], ['k.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_k_plaintiffs_case_number', 'k_plaintiffs', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('k_related_persons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('party_type', sa.String(), nullable=True),
    sa.Column('party_number', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('business_org_name', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_number'], ['k.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_k_related_persons_case_number', 'k_related_persons', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('k_sentencing_net_tools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serve_time_years', sa.Integer(), nullable=True),
    sa.Column('serve_time_months', sa.Integer(), nullable=True),
    sa.Column('serve_time_days', sa.Integer(), nullable=True),
    sa.Column('serve_time_hours', sa.Integer(), nullable=True),
    sa.Column('probation_years', sa.Integer(), nullable=True),
    sa.Column('probation_months', sa.Integer(), nullable=True),
    sa.Column('probation_days', sa.Integer(), nullable=True),
    sa.Column('probation_hours', sa.Integer(), nullable=True),
    sa.Column('fine_amount', sa.Numeric(), nullable=True),
    sa.Column('fine_due_date_str', sa.String(), nullable=True),
    sa.Column('fine_due_date', sa.Date(), nullable=True),
    sa.Column('cws_hours', sa.Integer(), nullable=True),
    sa.Column('credit_time_served', sa.Integer(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_number'], ['k.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('k_support_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('order_date', sa.Date(), nullable=True),
    sa.Column('order_date_str', sa.String(), nullable=True),
    sa.Column('obligor', sa.String(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('effective_date_str', sa.String(), nullable=True),
    sa.Column('effective_date_text', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('date_str', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('support_amount', sa.Numeric(), nullable=True),
    sa.Column('support_frequency', sa.String(), nullable=True),
    sa.Column('support_to', sa.String(), nullable=True),
    sa.Column('arrears_amount', sa.Numeric(), nullable=True),
    sa.Column('arrears_frequency', sa.String(), nullable=True),
    sa.Column('arrears_to', sa.String(), nullable=True),
    sa.Column('mapr_amount', sa.Numeric(), nullable=True),
    sa.Column('mapr_frequency', sa.String(), nullable=True),
    sa.Column('medical_insurance_report_date', sa.Date(), nullable=True),
    sa.Column('medical_insurance_report_date_str', sa.String(), nullable=True),
    sa.Column('btr_amount', sa.Numeric(), nullable=True),
    sa.Column('btr_frequency', sa.String(), nullable=True),
    sa.Column('lien', sa.String(), nullable=True),
    sa.Column('provisions', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_number'], ['k.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_k_support_orders_case_number', 'k_support_orders', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('k_attorneys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plaintiff_id', sa.Integer(), nullable=True),
    sa.Column('defendant_id', sa.Integer(), nullable=True),
    sa.Column('related_person_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('appearance_date', sa.Date(), nullable=True),
    sa.Column('appearance_date_str', sa.String(), nullable=True),
    sa.Column('removal_date', sa.Date(), nullable=True),
    sa.Column('removal_date_str', sa.String(), nullable=True),
    sa.Column('practice_name', sa.String(), nullable=True),
    sa.Column('address_1', sa.String(), nullable=True),
    sa.Column('address_2', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_number'], ['k.case_number'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['defendant_id'], ['k_defendants.id'], ),
    sa.ForeignKeyConstraint(['plaintiff_id'], ['k_plaintiffs.id'], ),
    sa.ForeignKeyConstraint(['related_person_id'], ['k_related_persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_k_attorneys_case_number', 'k_attorneys', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('k_judgment_modifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('judgment_id', sa.Integer(), nullable=True),
    sa.Column('judgment_against', sa.String(), nullable=True),
    sa.Column('judgment_for', sa.String(), nullable=True),
    sa.Column('entered_date', sa.Date(), nullable=True),
    sa.Column('entered_date_str', sa.String(), nullable=True),
    sa.Column('amount', sa.Numeric(), nullable=True),
    sa.Column('amount_other', sa.String(), nullable=True),
    sa.Column('status_date', sa.Date(), nullable=True),
    sa.Column('status_date_str', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_number'], ['k.case_number'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['judgment_id'], ['k_judgments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_k_judgment_modifications_case_number', 'k_judgment_modifications', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('k_judgments_against',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('judgment_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_number'], ['k.case_number'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['judgment_id'], ['k_judgments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_k_judgments_against_case_number', 'k_judgments_against', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('k_judgments_in_favor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('judgment_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_number'], ['k.case_number'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['judgment_id'], ['k_judgments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_k_judgments_in_favor_case_number', 'k_judgments_in_favor', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('k_party_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plaintiff_id', sa.Integer(), nullable=True),
    sa.Column('defendant_id', sa.Integer(), nullable=True),
    sa.Column('related_person_id', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_number'], ['k.case_number'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['defendant_id'], ['k_defendants.id'], ),
    sa.ForeignKeyConstraint(['plaintiff_id'], ['k_plaintiffs.id'], ),
    sa.ForeignKeyConstraint(['related_person_id'], ['k_related_persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_k_party_addresses_case_number', 'k_party_addresses', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('k_party_alias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plaintiff_id', sa.Integer(), nullable=True),
    sa.Column('defendant_id', sa.Integer(), nullable=True),
    sa.Column('related_person_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_number'], ['k.case_number'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['defendant_id'], ['k_defendants.id'], ),
    sa.ForeignKeyConstraint(['plaintiff_id'], ['k_plaintiffs.id'], ),
    sa.ForeignKeyConstraint(['related_person_id'], ['k_related_persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_k_party_alias_case_number', 'k_party_alias', ['case_number'], unique=False, postgresql_using='hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ixh_k_party_alias_case_number', table_name='k_party_alias', postgresql_using='hash')
    op.drop_table('k_party_alias')
    op.drop_index('ixh_k_party_addresses_case_number', table_name='k_party_addresses', postgresql_using='hash')
    op.drop_table('k_party_addresses')
    op.drop_index('ixh_k_judgments_in_favor_case_number', table_name='k_judgments_in_favor', postgresql_using='hash')
    op.drop_table('k_judgments_in_favor')
    op.drop_index('ixh_k_judgments_against_case_number', table_name='k_judgments_against', postgresql_using='hash')
    op.drop_table('k_judgments_against')
    op.drop_index('ixh_k_judgment_modifications_case_number', table_name='k_judgment_modifications', postgresql_using='hash')
    op.drop_table('k_judgment_modifications')
    op.drop_index('ixh_k_attorneys_case_number', table_name='k_attorneys', postgresql_using='hash')
    op.drop_table('k_attorneys')
    op.drop_index('ixh_k_support_orders_case_number', table_name='k_support_orders', postgresql_using='hash')
    op.drop_table('k_support_orders')
    op.drop_table('k_sentencing_net_tools')
    op.drop_index('ixh_k_related_persons_case_number', table_name='k_related_persons', postgresql_using='hash')
    op.drop_table('k_related_persons')
    op.drop_index('ixh_k_plaintiffs_case_number', table_name='k_plaintiffs', postgresql_using='hash')
    op.drop_table('k_plaintiffs')
    op.drop_index('ixh_k_judgments_case_number', table_name='k_judgments', postgresql_using='hash')
    op.drop_table('k_judgments')
    op.drop_index('ixh_k_documents_case_number', table_name='k_documents', postgresql_using='hash')
    op.drop_table('k_documents')
    op.drop_index('ixh_k_district_case_numbers_case_number', table_name='k_district_case_numbers', postgresql_using='hash')
    op.drop_table('k_district_case_numbers')
    op.drop_index('ixh_k_defendants_case_number', table_name='k_defendants', postgresql_using='hash')
    op.drop_table('k_defendants')
    op.drop_index('ixh_k_court_schedule_case_number', table_name='k_court_schedule', postgresql_using='hash')
    op.drop_table('k_court_schedule')
    op.drop_index('ixh_k_charges_case_number', table_name='k_charges', postgresql_using='hash')
    op.drop_table('k_charges')
    op.drop_index('ixh_k_case_number', table_name='k', postgresql_using='hash')
    op.drop_table('k')
    # ### end Alembic commands ###
