"""Add bail bond information to ODYTRAF tables

Revision ID: d66528af89f3
Revises: 795bdb9f58e3
Create Date: 2019-04-11 15:57:25.917635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd66528af89f3'
down_revision = '795bdb9f58e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('odytraf_bail_bonds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bond_type', sa.String(), nullable=True),
    sa.Column('bond_amount_set', sa.String(), nullable=True),
    sa.Column('bond_status_date', sa.Date(), nullable=True),
    sa.Column('bond_status_date_str', sa.String(), nullable=True),
    sa.Column('bond_status', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_number'], ['odytraf.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_odytraf_bail_bonds_case_number'), 'odytraf_bail_bonds', ['case_number'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_odytraf_bail_bonds_case_number'), table_name='odytraf_bail_bonds')
    op.drop_table('odytraf_bail_bonds')
    # ### end Alembic commands ###
