"""ODYCRIM and ODYTRAF fixes

Revision ID: d74fb94c58b2
Revises: 0ab508b55023
Create Date: 2020-05-14 11:13:06.085567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd74fb94c58b2'
down_revision = '7dba91c1c6c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('odytraf_charges', sa.Column('jail_suspended_term', sa.String(), nullable=True))
    op.add_column('odycrim_restitutions', sa.Column('other_cost_amount', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('odycrim_restitutions', 'other_cost_amount')
    op.drop_column('odytraf_charges', 'jail_suspended_term')
    # ### end Alembic commands ###
