"""name and party_type for odycivil_involved_parties can be nullable

Revision ID: d8738272f350
Revises: 2ca606c7a07c
Create Date: 2021-07-03 17:04:08.503286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8738272f350'
down_revision = '93332e9c34d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('odycivil_involved_parties', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('odycivil_involved_parties', 'party_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('odycivil_involved_parties', 'party_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('odycivil_involved_parties', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
