"""Remove unused indices

Revision ID: d9fdeb7de827
Revises: 193c09af9eb1
Create Date: 2021-09-30 08:17:44.382303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9fdeb7de827'
down_revision = '193c09af9eb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cases_detail_loc', table_name='cases')
    op.drop_index('ix_cases_last_parse', table_name='cases')
    op.drop_index('ix_cases_last_scrape', table_name='cases')
    op.drop_index('ixh_cases_detail_loc', table_name='cases')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ixh_cases_detail_loc', 'cases', ['detail_loc'], unique=False)
    op.create_index('ix_cases_last_scrape', 'cases', ['last_scrape'], unique=False)
    op.create_index('ix_cases_last_parse', 'cases', ['last_parse'], unique=False)
    op.create_index('ix_cases_detail_loc', 'cases', ['detail_loc'], unique=False)
    # ### end Alembic commands ###
