"""Add pop_award_to field to odycivil_judgment_comments

Revision ID: da56ed9c2ee4
Revises: a6437e172d13
Create Date: 2021-03-02 12:42:36.206857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da56ed9c2ee4'
down_revision = 'a6437e172d13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('odycivil_judgment_comments', sa.Column('pop_award_to', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('odycivil_judgment_comments', 'pop_award_to')
    # ### end Alembic commands ###
