"""Added DSTRAF models

Revision ID: e12e27cc98a6
Revises: aed623153eb1
Create Date: 2021-07-19 19:25:59.241008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e12e27cc98a6'
down_revision = 'aed623153eb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dstraf',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('court_system', sa.String(), nullable=True),
    sa.Column('citation_number', sa.String(), nullable=True),
    sa.Column('district_code', sa.Integer(), nullable=True),
    sa.Column('location_code', sa.Integer(), nullable=True),
    sa.Column('violation_date', sa.Date(), nullable=True),
    sa.Column('violation_date_str', sa.String(), nullable=True),
    sa.Column('violation_time', sa.Time(), nullable=True),
    sa.Column('violation_time_str', sa.String(), nullable=True),
    sa.Column('violation_county', sa.String(), nullable=True),
    sa.Column('agency_name', sa.String(), nullable=True),
    sa.Column('officer_id', sa.String(), nullable=True),
    sa.Column('officer_name', sa.String(), nullable=True),
    sa.Column('case_status', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_number'], ['cases.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_number')
    )
    op.create_index('ixh_dstraf_case_number', 'dstraf', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('dstraf_charges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('charge', sa.String(), nullable=True),
    sa.Column('article', sa.String(), nullable=True),
    sa.Column('sec', sa.Integer(), nullable=True),
    sa.Column('sub_sec', sa.String(), nullable=True),
    sa.Column('para', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('speed_limit', sa.Integer(), nullable=True),
    sa.Column('recorded_speed', sa.Integer(), nullable=True),
    sa.Column('location_stopped', sa.String(), nullable=True),
    sa.Column('contributed_to_accident', sa.String(), nullable=True),
    sa.Column('personal_injury', sa.String(), nullable=True),
    sa.Column('property_damage', sa.String(), nullable=True),
    sa.Column('seat_belts', sa.String(), nullable=True),
    sa.Column('fine', sa.Numeric(), nullable=True),
    sa.Column('related_citation_number', sa.String(), nullable=True),
    sa.Column('vehicle_tag', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('vehicle_description', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_number'], ['dstraf.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_dstraf_charges_case_number', 'dstraf_charges', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('dstraf_defendants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('race', sa.String(), nullable=True),
    sa.Column('sex', sa.String(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('DOB', sa.Date(), nullable=True),
    sa.Column('DOB_str', sa.String(), nullable=True),
    sa.Column('address_1', sa.String(), nullable=True),
    sa.Column('address_2', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_number'], ['dstraf.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_dstraf_defendants_case_number', 'dstraf_defendants', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('dstraf_dispositions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plea', sa.String(), nullable=True),
    sa.Column('disposition', sa.String(), nullable=True),
    sa.Column('disposition_date', sa.Date(), nullable=True),
    sa.Column('disposition_date_str', sa.String(), nullable=True),
    sa.Column('speed_limit', sa.Integer(), nullable=True),
    sa.Column('convicted_speed', sa.Integer(), nullable=True),
    sa.Column('contributed_to_accident', sa.String(), nullable=True),
    sa.Column('alcohol_restriction', sa.String(), nullable=True),
    sa.Column('personal_injury', sa.String(), nullable=True),
    sa.Column('alcohol_education', sa.String(), nullable=True),
    sa.Column('driver_improvement', sa.String(), nullable=True),
    sa.Column('sentence_date', sa.Date(), nullable=True),
    sa.Column('sentence_date_str', sa.String(), nullable=True),
    sa.Column('sentence_years', sa.Integer(), nullable=True),
    sa.Column('sentence_months', sa.Integer(), nullable=True),
    sa.Column('sentence_days', sa.Integer(), nullable=True),
    sa.Column('suspended_years', sa.Integer(), nullable=True),
    sa.Column('suspended_months', sa.Integer(), nullable=True),
    sa.Column('suspended_days', sa.Integer(), nullable=True),
    sa.Column('sentence_starts', sa.Date(), nullable=True),
    sa.Column('sentence_starts_str', sa.String(), nullable=True),
    sa.Column('probation_type', sa.String(), nullable=True),
    sa.Column('fine', sa.Numeric(), nullable=True),
    sa.Column('court_costs', sa.Numeric(), nullable=True),
    sa.Column('cicf', sa.Numeric(), nullable=True),
    sa.Column('suspended_fine', sa.Numeric(), nullable=True),
    sa.Column('suspended_court_costs', sa.Numeric(), nullable=True),
    sa.Column('suspended_cicf', sa.Numeric(), nullable=True),
    sa.Column('addition_statement', sa.String(), nullable=True),
    sa.Column('addition_charge', sa.String(), nullable=True),
    sa.Column('addition_article', sa.String(), nullable=True),
    sa.Column('addition_sec', sa.Integer(), nullable=True),
    sa.Column('addition_sub_sec', sa.String(), nullable=True),
    sa.Column('addiiton_para', sa.String(), nullable=True),
    sa.Column('addition_code', sa.String(), nullable=True),
    sa.Column('addition_amended_charge', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_number'], ['dstraf.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_dstraf_dispositions_case_number', 'dstraf_dispositions', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('dstraf_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('date_str', sa.String(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_number'], ['dstraf.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_dstraf_events_case_number', 'dstraf_events', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('dstraf_related_persons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('connection', sa.String(), nullable=True),
    sa.Column('address_1', sa.String(), nullable=True),
    sa.Column('address_2', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('agency_code', sa.String(), nullable=True),
    sa.Column('agency_sub_code', sa.String(), nullable=True),
    sa.Column('officer_id', sa.String(), nullable=True),
    sa.Column('attorney_code', sa.Integer(), nullable=True),
    sa.Column('attorney_firm', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_number'], ['dstraf.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_dstraf_related_persons_case_number', 'dstraf_related_persons', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('dstraf_trials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('date_str', sa.String(), nullable=True),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('time_str', sa.String(), nullable=True),
    sa.Column('room', sa.String(), nullable=True),
    sa.Column('trial_type', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_number'], ['dstraf.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_dstraf_trials_case_number', 'dstraf_trials', ['case_number'], unique=False, postgresql_using='hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ixh_dstraf_trials_case_number', table_name='dstraf_trials', postgresql_using='hash')
    op.drop_table('dstraf_trials')
    op.drop_index('ixh_dstraf_related_persons_case_number', table_name='dstraf_related_persons', postgresql_using='hash')
    op.drop_table('dstraf_related_persons')
    op.drop_index('ixh_dstraf_events_case_number', table_name='dstraf_events', postgresql_using='hash')
    op.drop_table('dstraf_events')
    op.drop_index('ixh_dstraf_dispositions_case_number', table_name='dstraf_dispositions', postgresql_using='hash')
    op.drop_table('dstraf_dispositions')
    op.drop_index('ixh_dstraf_defendants_case_number', table_name='dstraf_defendants', postgresql_using='hash')
    op.drop_table('dstraf_defendants')
    op.drop_index('ixh_dstraf_charges_case_number', table_name='dstraf_charges', postgresql_using='hash')
    op.drop_table('dstraf_charges')
    op.drop_index('ixh_dstraf_case_number', table_name='dstraf', postgresql_using='hash')
    op.drop_table('dstraf')
    # ### end Alembic commands ###
