"""Generalize Alias model in ODYTRAF

Revision ID: e3c22bdd609b
Revises: ad575f796294
Create Date: 2019-04-14 12:23:49.403445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3c22bdd609b'
down_revision = 'ad575f796294'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('odytraf_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(), nullable=False),
    sa.Column('alias_type', sa.String(), nullable=False),
    sa.Column('defendant_id', sa.Integer(), nullable=True),
    sa.Column('bondsman_id', sa.Integer(), nullable=True),
    sa.Column('surety_id', sa.Integer(), nullable=True),
    sa.Column('probation_officer_id', sa.Integer(), nullable=True),
    sa.Column('interpreter_id', sa.Integer(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['bondsman_id'], ['odytraf_defendants.id'], ),
    sa.ForeignKeyConstraint(['case_number'], ['odytraf.case_number'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['defendant_id'], ['odytraf_defendants.id'], ),
    sa.ForeignKeyConstraint(['interpreter_id'], ['odytraf_defendants.id'], ),
    sa.ForeignKeyConstraint(['probation_officer_id'], ['odytraf_defendants.id'], ),
    sa.ForeignKeyConstraint(['surety_id'], ['odytraf_defendants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_odytraf_aliases_case_number'), 'odytraf_aliases', ['case_number'], unique=False)
    op.drop_index('ix_odytraf_defendant_aliases_case_number', table_name='odytraf_defendant_aliases')
    op.drop_table('odytraf_defendant_aliases')
    op.add_column('odytraf_bondsmen', sa.Column('address_1', sa.String(), nullable=True))
    op.add_column('odytraf_bondsmen', sa.Column('address_2', sa.String(), nullable=True))
    op.drop_column('odytraf_bondsmen', 'address')
    op.add_column('odytraf_interpreters', sa.Column('address_1', sa.String(), nullable=True))
    op.add_column('odytraf_interpreters', sa.Column('address_2', sa.String(), nullable=True))
    op.drop_column('odytraf_interpreters', 'address')
    op.add_column('odytraf_probation_officers', sa.Column('address_1', sa.String(), nullable=True))
    op.add_column('odytraf_probation_officers', sa.Column('address_2', sa.String(), nullable=True))
    op.drop_column('odytraf_probation_officers', 'address')
    op.add_column('odytraf_sureties', sa.Column('address_1', sa.String(), nullable=True))
    op.add_column('odytraf_sureties', sa.Column('address_2', sa.String(), nullable=True))
    op.drop_column('odytraf_sureties', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('odytraf_sureties', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('odytraf_sureties', 'address_2')
    op.drop_column('odytraf_sureties', 'address_1')
    op.add_column('odytraf_probation_officers', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('odytraf_probation_officers', 'address_2')
    op.drop_column('odytraf_probation_officers', 'address_1')
    op.add_column('odytraf_interpreters', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('odytraf_interpreters', 'address_2')
    op.drop_column('odytraf_interpreters', 'address_1')
    op.add_column('odytraf_bondsmen', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('odytraf_bondsmen', 'address_2')
    op.drop_column('odytraf_bondsmen', 'address_1')
    op.create_table('odytraf_defendant_aliases',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('alias', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('alias_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('case_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['case_number'], ['odytraf.case_number'], name='odytraf_defendant_aliases_case_number_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='odytraf_defendant_aliases_pkey')
    )
    op.create_index('ix_odytraf_defendant_aliases_case_number', 'odytraf_defendant_aliases', ['case_number'], unique=False)
    op.drop_index(op.f('ix_odytraf_aliases_case_number'), table_name='odytraf_aliases')
    op.drop_table('odytraf_aliases')
    # ### end Alembic commands ###
