"""change data type in dscr

Revision ID: e3ca8834d437
Revises: aeac150f0048
Create Date: 2018-05-23 16:39:40.712771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3ca8834d437'
down_revision = 'aeac150f0048'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dscr','tracking_number',type_=sa.String)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dscr','tracking_number',type_=sa.BigInteger)
    # ### end Alembic commands ###
