"""Restore foreign key relationships bw charges and 2nd tier models

Revision ID: e81039c4f948
Revises: 1c01c67345db
Create Date: 2021-07-30 17:25:35.370361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e81039c4f948'
down_revision = '1c01c67345db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'dscr_charges', 'dscr', ['case_number'], ['case_number'], ondelete='CASCADE')
    op.create_foreign_key(None, 'dsk8_charges', 'dsk8', ['case_number'], ['case_number'], ondelete='CASCADE')
    op.create_foreign_key(None, 'odycrim_charges', 'odycrim', ['case_number'], ['case_number'], ondelete='CASCADE')
    op.create_foreign_key(None, 'odycvcit_charges', 'odycvcit', ['case_number'], ['case_number'], ondelete='CASCADE')
    op.create_foreign_key(None, 'odytraf_charges', 'odytraf', ['case_number'], ['case_number'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'odytraf_charges', type_='foreignkey')
    op.drop_constraint(None, 'odycvcit_charges', type_='foreignkey')
    op.drop_constraint(None, 'odycrim_charges', type_='foreignkey')
    op.drop_constraint(None, 'dsk8_charges', type_='foreignkey')
    op.drop_constraint(None, 'dscr_charges', type_='foreignkey')
    # ### end Alembic commands ###
