"""Add DSCP models

Revision ID: e8ac4686db0c
Revises: b1570fa6c264
Create Date: 2021-08-23 03:21:59.007544

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e8ac4686db0c'
down_revision = '1d128fd0312c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dscp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('court_system', sa.String(), nullable=True),
    sa.Column('tracking_number', sa.String(), nullable=True),
    sa.Column('case_type', sa.String(), nullable=True),
    sa.Column('district_code', sa.Integer(), nullable=True),
    sa.Column('location_code', sa.Integer(), nullable=True),
    sa.Column('document_type', sa.String(), nullable=True),
    sa.Column('issued_date', sa.Date(), nullable=True),
    sa.Column('issued_date_str', sa.String(), nullable=True),
    sa.Column('case_status', sa.String(), nullable=True),
    sa.Column('case_disposition', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_number'], ['cases.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_number')
    )
    op.create_index('ixh_dscp_case_number', 'dscp', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('dscp_bail_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('date_str', sa.String(), nullable=True),
    sa.Column('bail_amount', sa.Numeric(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('percentage_required', sa.Numeric(), nullable=True),
    sa.Column('type_of_bond', sa.String(), nullable=True),
    sa.Column('judge_id', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_number'], ['dscp.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_dscp_bail_events_case_number', 'dscp_bail_events', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('dscp_charges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('charge_number', sa.Integer(), nullable=True),
    sa.Column('expunged', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('charge_description', sa.String(), nullable=True),
    sa.Column('statute', sa.String(), nullable=True),
    sa.Column('statute_description', sa.String(), nullable=True),
    sa.Column('amended_date', sa.Date(), nullable=True),
    sa.Column('amended_date_str', sa.String(), nullable=True),
    sa.Column('cjis_code', sa.String(), nullable=True),
    sa.Column('mo_pll', sa.String(), nullable=True),
    sa.Column('probable_cause', sa.Boolean(), nullable=True),
    sa.Column('incident_date_from', sa.Date(), nullable=True),
    sa.Column('incident_date_from_str', sa.String(), nullable=True),
    sa.Column('incident_date_to', sa.Date(), nullable=True),
    sa.Column('incident_date_to_str', sa.String(), nullable=True),
    sa.Column('victim_age', sa.Integer(), nullable=True),
    sa.Column('plea', sa.String(), nullable=True),
    sa.Column('disposition', sa.String(), nullable=True),
    sa.Column('disposition_date', sa.Date(), nullable=True),
    sa.Column('disposition_date_str', sa.String(), nullable=True),
    sa.Column('fine', sa.Numeric(), nullable=True),
    sa.Column('court_costs', sa.Numeric(), nullable=True),
    sa.Column('cicf', sa.Numeric(), nullable=True),
    sa.Column('suspended_fine', sa.Numeric(), nullable=True),
    sa.Column('suspended_court_costs', sa.Numeric(), nullable=True),
    sa.Column('suspended_cicf', sa.Numeric(), nullable=True),
    sa.Column('pbj_end_date', sa.Date(), nullable=True),
    sa.Column('pbj_end_date_str', sa.String(), nullable=True),
    sa.Column('probation_end_date', sa.Date(), nullable=True),
    sa.Column('probation_end_date_str', sa.String(), nullable=True),
    sa.Column('restitution_amount', sa.Numeric(), nullable=True),
    sa.Column('jail_term_years', sa.Integer(), nullable=True),
    sa.Column('jail_term_months', sa.Integer(), nullable=True),
    sa.Column('jail_term_days', sa.Integer(), nullable=True),
    sa.Column('suspended_term_years', sa.Integer(), nullable=True),
    sa.Column('suspended_term_months', sa.Integer(), nullable=True),
    sa.Column('suspended_term_days', sa.Integer(), nullable=True),
    sa.Column('credit_time_served', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_number'], ['dscp.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_dscp_charges_case_number', 'dscp_charges', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('dscp_defendant_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alias_name', sa.String(), nullable=True),
    sa.Column('address_1', sa.String(), nullable=True),
    sa.Column('address_2', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_number'], ['dscp.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_dscp_defendant_aliases_case_number', 'dscp_defendant_aliases', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('dscp_defendants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('race', sa.String(), nullable=True),
    sa.Column('sex', sa.String(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('DOB', sa.Date(), nullable=True),
    sa.Column('DOB_str', sa.String(), nullable=True),
    sa.Column('address_1', sa.String(), nullable=True),
    sa.Column('address_2', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_number'], ['dscp.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_dscp_defendants_case_number', 'dscp_defendants', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('dscp_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('date_str', sa.String(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_number'], ['dscp.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_dscp_events_case_number', 'dscp_events', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('dscp_related_persons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('connection', sa.String(), nullable=True),
    sa.Column('address_1', sa.String(), nullable=True),
    sa.Column('address_2', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('agency_code', sa.String(), nullable=True),
    sa.Column('agency_sub_code', sa.String(), nullable=True),
    sa.Column('officer_id', sa.String(), nullable=True),
    sa.Column('attorney_code', sa.Integer(), nullable=True),
    sa.Column('attorney_firm', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_number'], ['dscp.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_dscp_related_persons_case_number', 'dscp_related_persons', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('dscp_trials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('date_str', sa.String(), nullable=True),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('time_str', sa.String(), nullable=True),
    sa.Column('room', sa.String(), nullable=True),
    sa.Column('trial_type', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_number'], ['dscp.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_dscp_trials_case_number', 'dscp_trials', ['case_number'], unique=False, postgresql_using='hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ixh_dscp_trials_case_number', table_name='dscp_trials', postgresql_using='hash')
    op.drop_table('dscp_trials')
    op.drop_index('ixh_dscp_related_persons_case_number', table_name='dscp_related_persons', postgresql_using='hash')
    op.drop_table('dscp_related_persons')
    op.drop_index('ixh_dscp_events_case_number', table_name='dscp_events', postgresql_using='hash')
    op.drop_table('dscp_events')
    op.drop_index('ixh_dscp_defendants_case_number', table_name='dscp_defendants', postgresql_using='hash')
    op.drop_table('dscp_defendants')
    op.drop_index('ixh_dscp_defendant_aliases_case_number', table_name='dscp_defendant_aliases', postgresql_using='hash')
    op.drop_table('dscp_defendant_aliases')
    op.drop_index('ixh_dscp_charges_case_number', table_name='dscp_charges', postgresql_using='hash')
    op.drop_table('dscp_charges')
    op.drop_index('ixh_dscp_bail_events_case_number', table_name='dscp_bail_events', postgresql_using='hash')
    op.drop_table('dscp_bail_events')
    op.drop_index('ixh_dscp_case_number', table_name='dscp', postgresql_using='hash')
    op.drop_table('dscp')
    # ### end Alembic commands ###
