"""Add appearance and removal dates to ODYTRAFF parties

Revision ID: eb90f8b96ee4
Revises: 025ecad5c330
Create Date: 2021-03-02 18:25:50.680647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb90f8b96ee4'
down_revision = '025ecad5c330'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('odytraf_attorneys', sa.Column('appearance_date', sa.Date(), nullable=True))
    op.add_column('odytraf_attorneys', sa.Column('appearance_date_str', sa.String(), nullable=True))
    op.add_column('odytraf_attorneys', sa.Column('removal_date', sa.Date(), nullable=True))
    op.add_column('odytraf_attorneys', sa.Column('removal_date_str', sa.String(), nullable=True))
    op.add_column('odytraf_involved_parties', sa.Column('appearance_date', sa.Date(), nullable=True))
    op.add_column('odytraf_involved_parties', sa.Column('appearance_date_str', sa.String(), nullable=True))
    op.add_column('odytraf_involved_parties', sa.Column('removal_date', sa.Date(), nullable=True))
    op.add_column('odytraf_involved_parties', sa.Column('removal_date_str', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('odytraf_involved_parties', 'removal_date_str')
    op.drop_column('odytraf_involved_parties', 'removal_date')
    op.drop_column('odytraf_involved_parties', 'appearance_date_str')
    op.drop_column('odytraf_involved_parties', 'appearance_date')
    op.drop_column('odytraf_attorneys', 'removal_date_str')
    op.drop_column('odytraf_attorneys', 'removal_date')
    op.drop_column('odytraf_attorneys', 'appearance_date_str')
    op.drop_column('odytraf_attorneys', 'appearance_date')
    # ### end Alembic commands ###
