"""Add site field to searches and runs

Revision ID: ec14982d61de
Revises: f7b524db073b
Create Date: 2020-03-21 16:15:02.413672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec14982d61de'
down_revision = 'f7b524db073b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queue', sa.Column('site', sa.String(), nullable=True))
    op.add_column('runs', sa.Column('site', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'site')
    op.drop_column('queue', 'site')
    # ### end Alembic commands ###
