"""fix to cc_judgments

Revision ID: eee1ab2826c0
Revises: 26b295254ad0
Create Date: 2018-05-21 11:00:12.699712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eee1ab2826c0'
down_revision = '26b295254ad0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cc_judgment_modifications', sa.Column('amount_other', sa.String(), nullable=True))
    op.add_column('cc_judgments', sa.Column('amount_other', sa.String(), nullable=True))
    op.add_column('cc_judgments', sa.Column('tij_other', sa.String(), nullable=True))
    op.drop_column('cc_judgments', 'tij_vehicle')
    op.drop_column('cc_judgments', 'amount_vehicle')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cc_judgments', sa.Column('amount_vehicle', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('cc_judgments', sa.Column('tij_vehicle', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('cc_judgments', 'tij_other')
    op.drop_column('cc_judgments', 'amount_other')
    op.drop_column('cc_judgment_modifications', 'amount_other')
    # ### end Alembic commands ###
