"""Add pg_defendants.party_number

Revision ID: f1d79c03a365
Revises: 5a9fc170dd16
Create Date: 2021-09-01 19:53:40.314268

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f1d79c03a365'
down_revision = '5a9fc170dd16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pg_defendants', sa.Column('party_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pg_defendants', 'party_number')
    # ### end Alembic commands ###
