"""Remove unused field in PG

Revision ID: f252364cce3d
Revises: c64263840760
Create Date: 2021-10-12 09:16:22.085164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f252364cce3d'
down_revision = 'c64263840760'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pg_attorneys', 'address_2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pg_attorneys', sa.Column('address_2', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
