"""Remove unused fields in ODYTRAF

Revision ID: f3606af6398f
Revises: b4f7a1413269
Create Date: 2021-10-11 15:25:04.463118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3606af6398f'
down_revision = 'b4f7a1413269'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('odytraf', 'officer_name')
    op.drop_column('odytraf', 'citation_number')
    op.drop_column('odytraf', 'officer_id')
    op.drop_column('odytraf', 'agency_name')
    op.drop_column('odytraf_charges', 'jail_life_death')
    op.drop_column('odytraf_documents', 'filed_by')
    op.drop_column('odytraf_involved_parties', 'appearance_date')
    op.drop_column('odytraf_involved_parties', 'removal_date')
    op.drop_column('odytraf_involved_parties', 'removal_date_str')
    op.drop_column('odytraf_involved_parties', 'appearance_date_str')
    op.drop_column('odytraf_services', 'service_status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('odytraf_services', sa.Column('service_status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('odytraf_involved_parties', sa.Column('appearance_date_str', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('odytraf_involved_parties', sa.Column('removal_date_str', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('odytraf_involved_parties', sa.Column('removal_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('odytraf_involved_parties', sa.Column('appearance_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('odytraf_documents', sa.Column('filed_by', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('odytraf_charges', sa.Column('jail_life_death', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('odytraf', sa.Column('agency_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('odytraf', sa.Column('officer_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('odytraf', sa.Column('citation_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('odytraf', sa.Column('officer_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
