"""possibly_expunged -> expunged

Revision ID: f39753ce0f30
Revises: b1203592827f
Create Date: 2021-07-26 22:12:18.459287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f39753ce0f30'
down_revision = 'b1203592827f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dscr_charges','possibly_expunged',new_column_name='expunged')
    op.alter_column('dsk8_charges','possibly_expunged',new_column_name='expunged')
    op.alter_column('odycrim_charges','possibly_expunged',new_column_name='expunged')
    op.alter_column('odycvcit_charges','possibly_expunged',new_column_name='expunged')
    op.alter_column('odytraf_charges','possibly_expunged',new_column_name='expunged')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dscr_charges','expunged',new_column_name='possibly_expunged')
    op.alter_column('dsk8_charges','expunged',new_column_name='possibly_expunged')
    op.alter_column('odycrim_charges','expunged',new_column_name='possibly_expunged')
    op.alter_column('odycvcit_charges','expunged',new_column_name='possibly_expunged')
    op.alter_column('odytraf_charges','expunged',new_column_name='possibly_expunged')
    # ### end Alembic commands ###
