"""Added filingfee and totalcosts to odycivil_judgment_comments

Revision ID: fa053738a6c7
Revises: 015bf4aefeac
Create Date: 2021-07-02 14:18:46.776731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa053738a6c7'
down_revision = '015bf4aefeac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('odycivil_judgment_comments', sa.Column('filingfee', sa.Numeric(), nullable=True))
    op.add_column('odycivil_judgment_comments', sa.Column('totalcosts', sa.Numeric(), nullable=True))
    op.add_column('odycivil_judgment_comments', sa.Column('postjinterest', sa.Numeric(), nullable=True))
    op.add_column('odycivil_judgment_comments', sa.Column('otherfee', sa.Numeric(), nullable=True))
    op.add_column('odycivil_judgment_comments', sa.Column('judg_ccjs_ind', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('odycivil_judgment_comments', 'judg_ccjs_ind')
    op.drop_column('odycivil_judgment_comments', 'otherfee')
    op.drop_column('odycivil_judgment_comments', 'postjinterest')
    op.drop_column('odycivil_judgment_comments', 'totalcosts')
    op.drop_column('odycivil_judgment_comments', 'filingfee')
    # ### end Alembic commands ###
