"""Add PG models

Revision ID: ff6daa02db69
Revises: 987da5298aca
Create Date: 2021-09-01 18:55:25.109888

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ff6daa02db69'
down_revision = '987da5298aca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pg',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('court_system', sa.String(), nullable=True),
    sa.Column('case_type', sa.String(), nullable=True),
    sa.Column('case_description', sa.String(), nullable=True),
    sa.Column('filing_date', sa.Date(), nullable=True),
    sa.Column('filing_date_str', sa.String(), nullable=True),
    sa.Column('case_status', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_number'], ['cases.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_number')
    )
    op.create_index('ixh_pg_case_number', 'pg', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('pg_attorneys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('attorney_type', sa.String(), nullable=True),
    sa.Column('address_1', sa.String(), nullable=True),
    sa.Column('address_2', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_number'], ['pg.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_pg_attorneys_case_number', 'pg_attorneys', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('pg_charges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('charge_number', sa.Integer(), nullable=True),
    sa.Column('expunged', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('charge', sa.String(), nullable=True),
    sa.Column('charge_code', sa.String(), nullable=True),
    sa.Column('offense_date', sa.Date(), nullable=True),
    sa.Column('offense_date_str', sa.String(), nullable=True),
    sa.Column('arrest_tracking_number', sa.String(), nullable=True),
    sa.Column('disposition', sa.String(), nullable=True),
    sa.Column('disposition_date', sa.Date(), nullable=True),
    sa.Column('disposition_date_str', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_number'], ['pg.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_pg_charges_case_number', 'pg_charges', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('pg_court_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('event_date_str', sa.String(), nullable=True),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('time_str', sa.String(), nullable=True),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('result_date', sa.Date(), nullable=True),
    sa.Column('result_date_str', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_number'], ['pg.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_pg_court_schedule_case_number', 'pg_court_schedule', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('pg_defendant_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alias_name', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_number'], ['pg.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_pg_defendant_aliases_case_number', 'pg_defendant_aliases', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('pg_defendants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address_1', sa.String(), nullable=True),
    sa.Column('address_2', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_number'], ['pg.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_pg_defendants_case_number', 'pg_defendants', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('pg_dockets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('date_str', sa.String(), nullable=True),
    sa.Column('document_name', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_number'], ['pg.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_pg_dockets_case_number', 'pg_dockets', ['case_number'], unique=False, postgresql_using='hash')
    op.create_table('pg_other_parties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('party_type', sa.String(), nullable=True),
    sa.Column('party_number', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_number'], ['pg.case_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ixh_pg_other_parties_case_number', 'pg_other_parties', ['case_number'], unique=False, postgresql_using='hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ixh_pg_other_parties_case_number', table_name='pg_other_parties', postgresql_using='hash')
    op.drop_table('pg_other_parties')
    op.drop_index('ixh_pg_dockets_case_number', table_name='pg_dockets', postgresql_using='hash')
    op.drop_table('pg_dockets')
    op.drop_index('ixh_pg_defendants_case_number', table_name='pg_defendants', postgresql_using='hash')
    op.drop_table('pg_defendants')
    op.drop_index('ixh_pg_defendant_aliases_case_number', table_name='pg_defendant_aliases', postgresql_using='hash')
    op.drop_table('pg_defendant_aliases')
    op.drop_index('ixh_pg_court_schedule_case_number', table_name='pg_court_schedule', postgresql_using='hash')
    op.drop_table('pg_court_schedule')
    op.drop_index('ixh_pg_charges_case_number', table_name='pg_charges', postgresql_using='hash')
    op.drop_table('pg_charges')
    op.drop_index('ixh_pg_attorneys_case_number', table_name='pg_attorneys', postgresql_using='hash')
    op.drop_table('pg_attorneys')
    op.drop_index('ixh_pg_case_number', table_name='pg', postgresql_using='hash')
    op.drop_table('pg')
    # ### end Alembic commands ###
